{
 "title": "t___Blitz_Server_Health_Analysis",
 "description": "Data of BlitzIndex",
 "tags": [
  "mssql",
  "sqlmonitor",
  "sp_Blitz"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "sqlmonitor_datasource", "label": "Data Source", "query": "mssql" },
   {
    "name": "server",
    "label": "Sql Instance",
    "query": "declare @sql nvarchar(max);\n\nset quoted_identifier off;\nset @sql = \"select distinct srvname = sql_instance from dbo.instance_details with (nolock)\nwhere is_available = 1 and is_enabled = 1\n\";\nset quoted_identifier off;\n\nexec dbo.sp_executesql @sql;"
   },
   { "name": "inventory_db", "label": "Inventory Database", "query": "SELECT DB_NAME()" },
   {
    "name": "is_local",
    "label": "Is Local SQL Instance",
    "query": "declare @sql_instance varchar(255); \nset @sql_instance = '$server';\nselect is_local = case when ( (CONVERT(varchar,SERVERPROPERTY('MachineName')) = @sql_instance ) \n\t\t\tor (CONVERT(varchar,SERVERPROPERTY('ServerName')) = @sql_instance )\n\t\t\t)  then 1 else 0 end"
   },
   {
    "name": "dba_db",
    "label": "DBA Database",
    "query": "declare @sql nvarchar(max);\ndeclare @sql_instance varchar(255);\nset @sql_instance = '$server';\n\nset quoted_identifier off;\nset @sql = \"select top 1 [database] from dbo.instance_details id\nwhere id.sql_instance = @sql_instance\n\";\nset quoted_identifier off;\n\nexec dbo.sp_executesql @sql, N'@sql_instance varchar(255)', @sql_instance;"
   },
   {
    "name": "ip",
    "label": "IP Address",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\n\nset @sql_instance = '$server';\nset @params = N'@sql_instance varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select CONVERT(varchar,  CONNECTIONPROPERTY('local_net_address') ) as [ip];\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql --, @params, @sql_instance;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql --, @params, @sql_instance;"
   },
   {
    "name": "fqdn",
    "label": "FQDN",
    "query": "exec dbo.usp_GetAllServerInfo \n\t\t\t\t@servers = '$server',\n\t\t\t\t@output = 'fqdn'"
   },
   {
    "name": "collection_time_utc",
    "label": "Collection Time UTC",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\n--declare @perfmon_host_name varchar(255);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\n--declare @delta_minutes int;\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\n--set @delta_minutes = $cpu_delta_minutes;\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2';\n\nset quoted_identifier off;\nset @sql = \"\nset nocount on;\nselect top 1 DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), CheckDate)\nfrom $blitz_table_name\norder by CheckDate desc\n\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc;"
   },
   {
    "name": "sql_schedulers",
    "label": "SQL Schedulers",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @params = N'@perfmon_host_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select count(*) as counts from sys.dm_os_schedulers dos where status = 'VISIBLE ONLINE' and is_online = 1;\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql , @params, @perfmon_host_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql , @params, @perfmon_host_name;"
   },
   {
    "name": "sqlserver_start_time_utc",
    "label": "SqlInstance Start Time UTC",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\n\nset @sql_instance = '$server';\nset @perfmon_host_name = '$perfmon_host_name';\nset @params = N'@perfmon_host_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), sqlserver_start_time) from sys.dm_os_sys_info as osi;\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql , @params, @perfmon_host_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql , @params, @perfmon_host_name;"
   },
   {
    "name": "disk_drive",
    "label": "Disk Drive",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @params = N'@perfmon_host_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select ds.disk_volume as disk_drive\n\tfrom dbo.disk_space ds\n\twhere ds.collection_time_utc = (select max(i.collection_time_utc) from dbo.disk_space i)\n\tunion all\n\tselect '__All__' as disk_drive\n\torder by disk_drive\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql , @params, @perfmon_host_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql , @params, @perfmon_host_name;"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @params = N'@perfmon_host_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select name from sys.databases d where d.state_desc = 'ONLINE' union all select '__All__' as name order by name;\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql , @params, @perfmon_host_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql , @params, @perfmon_host_name;"
   },
   { "name": "blitz_table_name", "label": "Blitz Table", "query": "${VAR_BLITZ_TABLE_NAME}" },
   { "name": "delta_days_threshold", "label": "Delta Days", "query": "5,10,15,20,30,60,90,180,365" },
   { "name": "page_no", "label": "Page No", "query": "1" },
   { "name": "page_size", "label": "Page Size", "query": "100" },
   { "name": "table_name", "label": "Table Name" },
   {
    "name": "priority",
    "label": "Priority",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @params = N'@perfmon_host_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select distinct Priority\nfrom $blitz_table_name b\nwhere b.CheckDate = (select top 1 CheckDate from dbo.Blitz order by CheckDate Desc)\nand (\tcase when FindingsGroup in ('Thanks!','Wait Stats')\n\t\t\tthen 0\n\t\t\twhen FindingsGroup like 'sp_Blitz %'\n\t\t\tthen 0\n\t\t\telse 1\n\t\t\tend ) = 1\nand Priority > 0\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql , @params, @perfmon_host_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql , @params, @perfmon_host_name;"
   },
   {
    "name": "finding_group",
    "label": "Finding Group",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @params = N'@perfmon_host_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select distinct FindingsGroup --Finding\nfrom $blitz_table_name b\nwhere b.CheckDate = (select top 1 CheckDate from dbo.Blitz order by CheckDate Desc)\nand (\tcase when FindingsGroup in ('Thanks!','Wait Stats')\n\t\t\tthen 0\n\t\t\twhen FindingsGroup like 'sp_Blitz %'\n\t\t\tthen 0\n\t\t\telse 1\n\t\t\tend ) = 1\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql , @params, @perfmon_host_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql , @params, @perfmon_host_name;"
   }
  ]
 },
 "panels": [
  {
   "title": "FindingsGroup = \"Reliability\" ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "FindingsGroup = 'Reliability' ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
     "type": "table",
     "description": "exec sp_Blitz",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255) = '$server';\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @delta_days_threshold int = ${delta_days_threshold};\ndeclare @buffer_days int = 2;\ndeclare @database varchar(255) = '$database';\ndeclare @page_no int;\ndeclare @page_size int;\ndeclare @table_name varchar(255);\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\nif len(ltrim(rtrim('$table_name'))) > 0\n  set @table_name = '$table_name'\n\nset @params = N'@database varchar(255), @delta_days_threshold int, @buffer_days int, @page_no int, @page_size int, @table_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - BlitzIndex Analysis - 0 Delta Rows */\nset nocount on;\n\nselect b.Priority, b.FindingsGroup, b.Finding, b.DatabaseName, b.URL, b.Details\nfrom $blitz_table_name b\nwhere b.CheckDate = (select top 1 CheckDate from $blitz_table_name order by CheckDate Desc)\nand (\tcase when FindingsGroup in ('Thanks!','Wait Stats')\n\t\t\tthen 0\n\t\t\twhen FindingsGroup like 'sp_Blitz %'\n\t\t\tthen 0\n\t\t\telse 1\n\t\t\tend ) = 1\nand FindingsGroup in ('Reliability')\n\"\nset quoted_identifier on;\n\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;"
      }
     ]
    }
   ]
  },
  {
   "title": "FindingsGroup = \"Security\" ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "FindingsGroup = 'Security' ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
     "type": "table",
     "description": "exec sp_Blitz",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255) = '$server';\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @delta_days_threshold int = ${delta_days_threshold};\ndeclare @buffer_days int = 2;\ndeclare @database varchar(255) = '$database';\ndeclare @page_no int;\ndeclare @page_size int;\ndeclare @table_name varchar(255);\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\nif len(ltrim(rtrim('$table_name'))) > 0\n  set @table_name = '$table_name'\n\nset @params = N'@database varchar(255), @delta_days_threshold int, @buffer_days int, @page_no int, @page_size int, @table_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - BlitzIndex Analysis - 0 Delta Rows */\nset nocount on;\n\nselect b.Priority, b.FindingsGroup, b.Finding, b.DatabaseName, b.URL, b.Details\nfrom $blitz_table_name b\nwhere b.CheckDate = (select top 1 CheckDate from $blitz_table_name order by CheckDate Desc)\nand (\tcase when FindingsGroup in ('Thanks!','Wait Stats')\n\t\t\tthen 0\n\t\t\twhen FindingsGroup like 'sp_Blitz %'\n\t\t\tthen 0\n\t\t\telse 1\n\t\t\tend ) = 1\nand FindingsGroup in ('Security')\n\"\nset quoted_identifier on;\n\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;"
      }
     ]
    }
   ]
  },
  {
   "title": "FindingsGroup = \"Performance\" ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "FindingsGroup = 'Performance' ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
     "type": "table",
     "description": "exec sp_Blitz",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255) = '$server';\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @delta_days_threshold int = ${delta_days_threshold};\ndeclare @buffer_days int = 2;\ndeclare @database varchar(255) = '$database';\ndeclare @page_no int;\ndeclare @page_size int;\ndeclare @table_name varchar(255);\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\nif len(ltrim(rtrim('$table_name'))) > 0\n  set @table_name = '$table_name'\n\nset @params = N'@database varchar(255), @delta_days_threshold int, @buffer_days int, @page_no int, @page_size int, @table_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - BlitzIndex Analysis - 0 Delta Rows */\nset nocount on;\n\nselect b.Priority, b.FindingsGroup, b.Finding, b.DatabaseName, b.URL, b.Details\nfrom $blitz_table_name b\nwhere b.CheckDate = (select top 1 CheckDate from $blitz_table_name order by CheckDate Desc)\nand (\tcase when FindingsGroup in ('Thanks!','Wait Stats')\n\t\t\tthen 0\n\t\t\twhen FindingsGroup like 'sp_Blitz %'\n\t\t\tthen 0\n\t\t\telse 1\n\t\t\tend ) = 1\nand FindingsGroup in ('Performance')\n\"\nset quoted_identifier on;\n\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;"
      }
     ]
    }
   ]
  },
  {
   "title": "FindingsGroup = \"Non-Default Database/Server Config\" ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "FindingsGroup = 'Non-Default Database/Server Config' ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
     "type": "table",
     "description": "exec sp_Blitz",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255) = '$server';\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @delta_days_threshold int = ${delta_days_threshold};\ndeclare @buffer_days int = 2;\ndeclare @database varchar(255) = '$database';\ndeclare @page_no int;\ndeclare @page_size int;\ndeclare @table_name varchar(255);\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\nif len(ltrim(rtrim('$table_name'))) > 0\n  set @table_name = '$table_name'\n\nset @params = N'@database varchar(255), @delta_days_threshold int, @buffer_days int, @page_no int, @page_size int, @table_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - BlitzIndex Analysis - 0 Delta Rows */\nset nocount on;\n\nselect b.Priority, b.FindingsGroup, b.Finding, b.DatabaseName, b.URL, b.Details\nfrom $blitz_table_name b\nwhere b.CheckDate = (select top 1 CheckDate from $blitz_table_name order by CheckDate Desc)\nand (\tcase when FindingsGroup in ('Thanks!','Wait Stats')\n\t\t\tthen 0\n\t\t\twhen FindingsGroup like 'sp_Blitz %'\n\t\t\tthen 0\n\t\t\telse 1\n\t\t\tend ) = 1\nand FindingsGroup in ('Non-Default Database Config','Non-Default Server Config','Non-Default Database Scoped Config')\n\"\nset quoted_identifier on;\n\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;"
      }
     ]
    }
   ]
  },
  {
   "title": "FindingsGroup = \"Backup\" ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "FindingsGroup = 'Backup' ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
     "type": "table",
     "description": "exec sp_Blitz",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255) = '$server';\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @delta_days_threshold int = ${delta_days_threshold};\ndeclare @buffer_days int = 2;\ndeclare @database varchar(255) = '$database';\ndeclare @page_no int;\ndeclare @page_size int;\ndeclare @table_name varchar(255);\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\nif len(ltrim(rtrim('$table_name'))) > 0\n  set @table_name = '$table_name'\n\nset @params = N'@database varchar(255), @delta_days_threshold int, @buffer_days int, @page_no int, @page_size int, @table_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - BlitzIndex Analysis - 0 Delta Rows */\nset nocount on;\n\nselect b.Priority, b.FindingsGroup, b.Finding, b.DatabaseName, b.URL, b.Details\nfrom $blitz_table_name b\nwhere b.CheckDate = (select top 1 CheckDate from $blitz_table_name order by CheckDate Desc)\nand (\tcase when FindingsGroup in ('Thanks!','Wait Stats')\n\t\t\tthen 0\n\t\t\twhen FindingsGroup like 'sp_Blitz %'\n\t\t\tthen 0\n\t\t\telse 1\n\t\t\tend ) = 1\nand FindingsGroup = 'Backup'\n\"\nset quoted_identifier on;\n\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;"
      }
     ]
    }
   ]
  },
  {
   "title": "FindingsGroup = \"File Configuration\" ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "FindingsGroup = 'File Configuration' ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
     "type": "table",
     "description": "exec sp_Blitz",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255) = '$server';\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @delta_days_threshold int = ${delta_days_threshold};\ndeclare @buffer_days int = 2;\ndeclare @database varchar(255) = '$database';\ndeclare @page_no int;\ndeclare @page_size int;\ndeclare @table_name varchar(255);\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\nif len(ltrim(rtrim('$table_name'))) > 0\n  set @table_name = '$table_name'\n\nset @params = N'@database varchar(255), @delta_days_threshold int, @buffer_days int, @page_no int, @page_size int, @table_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - BlitzIndex Analysis - 0 Delta Rows */\nset nocount on;\n\nselect b.Priority, b.FindingsGroup, b.Finding, b.DatabaseName, b.URL, b.Details\nfrom $blitz_table_name b\nwhere b.CheckDate = (select top 1 CheckDate from $blitz_table_name order by CheckDate Desc)\nand (\tcase when FindingsGroup in ('Thanks!','Wait Stats')\n\t\t\tthen 0\n\t\t\twhen FindingsGroup like 'sp_Blitz %'\n\t\t\tthen 0\n\t\t\telse 1\n\t\t\tend ) = 1\nand FindingsGroup = 'File Configuration'\n\"\nset quoted_identifier on;\n\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;"
      }
     ]
    }
   ]
  },
  {
   "title": "FindingsGroup = \"Monitoring\" ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "FindingsGroup = 'Monitoring' ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
     "type": "table",
     "description": "exec sp_Blitz",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255) = '$server';\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @delta_days_threshold int = ${delta_days_threshold};\ndeclare @buffer_days int = 2;\ndeclare @database varchar(255) = '$database';\ndeclare @page_no int;\ndeclare @page_size int;\ndeclare @table_name varchar(255);\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\nif len(ltrim(rtrim('$table_name'))) > 0\n  set @table_name = '$table_name'\n\nset @params = N'@database varchar(255), @delta_days_threshold int, @buffer_days int, @page_no int, @page_size int, @table_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - BlitzIndex Analysis - 0 Delta Rows */\nset nocount on;\n\nselect b.Priority, b.FindingsGroup, b.Finding, b.DatabaseName, b.URL, b.Details\nfrom $blitz_table_name b\nwhere b.CheckDate = (select top 1 CheckDate from $blitz_table_name order by CheckDate Desc)\nand (\tcase when FindingsGroup in ('Thanks!','Wait Stats')\n\t\t\tthen 0\n\t\t\twhen FindingsGroup like 'sp_Blitz %'\n\t\t\tthen 0\n\t\t\telse 1\n\t\t\tend ) = 1\nand FindingsGroup = 'Monitoring'\n\"\nset quoted_identifier on;\n\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;"
      }
     ]
    }
   ]
  },
  {
   "title": "FindingsGroup = \"Server Info\" ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "FindingsGroup = 'Server Info' ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
     "type": "table",
     "description": "exec sp_Blitz",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255) = '$server';\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @delta_days_threshold int = ${delta_days_threshold};\ndeclare @buffer_days int = 2;\ndeclare @database varchar(255) = '$database';\ndeclare @page_no int;\ndeclare @page_size int;\ndeclare @table_name varchar(255);\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\nif len(ltrim(rtrim('$table_name'))) > 0\n  set @table_name = '$table_name'\n\nset @params = N'@database varchar(255), @delta_days_threshold int, @buffer_days int, @page_no int, @page_size int, @table_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - BlitzIndex Analysis - 0 Delta Rows */\nset nocount on;\n\nselect b.Priority, b.FindingsGroup, b.Finding, b.DatabaseName, b.URL, b.Details\nfrom $blitz_table_name b\nwhere b.CheckDate = (select top 1 CheckDate from $blitz_table_name order by CheckDate Desc)\nand (\tcase when FindingsGroup in ('Thanks!','Wait Stats')\n\t\t\tthen 0\n\t\t\twhen FindingsGroup like 'sp_Blitz %'\n\t\t\tthen 0\n\t\t\telse 1\n\t\t\tend ) = 1\nand FindingsGroup in ('Server Info')\n\"\nset quoted_identifier on;\n\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;"
      }
     ]
    }
   ]
  },
  {
   "title": "FindingsGroup = \"Licensing\" ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "FindingsGroup = 'Licensing' ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
     "type": "table",
     "description": "exec sp_Blitz",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255) = '$server';\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @delta_days_threshold int = ${delta_days_threshold};\ndeclare @buffer_days int = 2;\ndeclare @database varchar(255) = '$database';\ndeclare @page_no int;\ndeclare @page_size int;\ndeclare @table_name varchar(255);\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\nif len(ltrim(rtrim('$table_name'))) > 0\n  set @table_name = '$table_name'\n\nset @params = N'@database varchar(255), @delta_days_threshold int, @buffer_days int, @page_no int, @page_size int, @table_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - BlitzIndex Analysis - 0 Delta Rows */\nset nocount on;\n\nselect b.Priority, b.FindingsGroup, b.Finding, b.DatabaseName, b.URL, b.Details\nfrom $blitz_table_name b\nwhere b.CheckDate = (select top 1 CheckDate from $blitz_table_name order by CheckDate Desc)\nand (\tcase when FindingsGroup in ('Thanks!','Wait Stats')\n\t\t\tthen 0\n\t\t\twhen FindingsGroup like 'sp_Blitz %'\n\t\t\tthen 0\n\t\t\telse 1\n\t\t\tend ) = 1\nand FindingsGroup = 'Licensing'\n\"\nset quoted_identifier on;\n\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;"
      }
     ]
    }
   ]
  },
  {
   "title": "FindingsGroup = \"Informational\" ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "FindingsGroup = 'Informational' ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
     "type": "table",
     "description": "exec sp_Blitz",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255) = '$server';\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @delta_days_threshold int = ${delta_days_threshold};\ndeclare @buffer_days int = 2;\ndeclare @database varchar(255) = '$database';\ndeclare @page_no int;\ndeclare @page_size int;\ndeclare @table_name varchar(255);\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\nif len(ltrim(rtrim('$table_name'))) > 0\n  set @table_name = '$table_name'\n\nset @params = N'@database varchar(255), @delta_days_threshold int, @buffer_days int, @page_no int, @page_size int, @table_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - BlitzIndex Analysis - 0 Delta Rows */\nset nocount on;\n\nselect b.Priority, b.FindingsGroup, b.Finding, b.DatabaseName, b.URL, b.Details\nfrom $blitz_table_name b\nwhere b.CheckDate = (select top 1 CheckDate from $blitz_table_name order by CheckDate Desc)\nand (\tcase when FindingsGroup in ('Thanks!','Wait Stats')\n\t\t\tthen 0\n\t\t\twhen FindingsGroup like 'sp_Blitz %'\n\t\t\tthen 0\n\t\t\telse 1\n\t\t\tend ) = 1\nand FindingsGroup = 'Informational'\n\"\nset quoted_identifier on;\n\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;"
      }
     ]
    }
   ]
  },
  {
   "title": "All - Server Health Analysis ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "sp_Blitz - Server Health Analysis ____@ ____${collection_time_utc:date:YYYY-MM-DD HH.mm}_____ - [$fqdn] - [$ip]",
     "type": "table",
     "description": "exec sp_Blitz",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255) = '$server';\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @delta_days_threshold int = ${delta_days_threshold};\ndeclare @buffer_days int = 2;\ndeclare @database varchar(255) = '$database';\ndeclare @page_no int;\ndeclare @page_size int;\ndeclare @table_name varchar(255);\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nif len(ltrim(rtrim('$page_no'))) > 0 and (case when '$page_no' like '%[^0-9.]%' then 'invalid' when '$page_no' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_no = convert(int,ltrim(rtrim('$page_no')));\nif len(ltrim(rtrim('$page_size'))) > 0 and (case when '$page_size' like '%[^0-9.]%' then 'invalid' when '$page_size' like '%.%.%' then 'invalid' else 'valid' end) = 'valid'\n  set @page_size = convert(int,ltrim(rtrim('$page_size')));\nif len(ltrim(rtrim('$table_name'))) > 0\n  set @table_name = '$table_name'\n\nset @params = N'@database varchar(255), @delta_days_threshold int, @buffer_days int, @page_no int, @page_size int, @table_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor - BlitzIndex Analysis - 0 Delta Rows */\nset nocount on;\n\nselect b.Priority, b.FindingsGroup, b.Finding, b.DatabaseName, b.URL, b.Details\nfrom $blitz_table_name b\nwhere b.CheckDate = (select top 1 CheckDate from $blitz_table_name order by CheckDate Desc)\nand (\tcase when FindingsGroup in ('Thanks!','Wait Stats')\n\t\t\tthen 0\n\t\t\twhen FindingsGroup like 'sp_Blitz %'\n\t\t\tthen 0\n\t\t\telse 1\n\t\t\tend ) = 1\n\"\nset quoted_identifier on;\n\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @database, @delta_days_threshold, @buffer_days, @page_no, @page_size, @table_name;"
      }
     ]
    }
   ]
  }
 ]
}