{
 "title": "XEvent - Trend",
 "description": "Display Workload Details Captured using Extended Events",
 "tags": [
  "mssql",
  "sqlmonitor",
  "XEvents"
 ],
 "time": { "from": "now-15d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "sqlmonitor_datasource", "label": "Data Source", "query": "mssql" },
   {
    "name": "server",
    "label": "Sql Instance",
    "query": "select distinct srvname = sql_instance from dbo.instance_details with (nolock)\nwhere is_available = 1 and is_enabled = 1"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @perfmon_host_name varchar(255);\n\nset @sql_instance = '$server';\n--set @perfmon_host_name = '$perfmon_host_name';\nset @params = N'@perfmon_host_name varchar(255)';\n\nset quoted_identifier off;\nset @sql = \"select name from sys.databases d where d.state_desc = 'ONLINE' union all select '__All__' as name order by name;\"\nset quoted_identifier on;\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql , @params, @perfmon_host_name;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql , @params, @perfmon_host_name;"
   },
   { "name": "inventory_db", "label": "Inventory Database", "query": "SELECT DB_NAME() as [db_name]" },
   {
    "name": "is_local",
    "label": "Is Local SQL Instance",
    "query": "declare @sql_instance varchar(255); \nset @sql_instance = '$server';\nselect is_local = case when ( (CONVERT(varchar,SERVERPROPERTY('MachineName')) = @sql_instance ) \n\t\t\tor (CONVERT(varchar,SERVERPROPERTY('ServerName')) = @sql_instance )\n\t\t\t)  then 1 else 0 end"
   },
   {
    "name": "ip",
    "label": "IP Address",
    "query": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\nselect CONVERT(varchar,  CONNECTIONPROPERTY('local_net_address') ) as [ip]\n\"\nSET QUOTED_IDENTIFIER ON\n\n--IF ('$server' = SERVERPROPERTY('ServerName'))\nif ($is_local = 1)\n  EXEC (@sql);\nELSE\n  EXEC (@sql) AT [$server];"
   },
   {
    "name": "host_name",
    "label": "Host Name",
    "query": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\nselect CONVERT(varchar,COALESCE(SERVERPROPERTY('ComputerNamePhysicalNetBIOS'),SERVERPROPERTY('ServerName'))) as [host_name]\n\"\nSET QUOTED_IDENTIFIER ON\n\n--IF ('$server' = SERVERPROPERTY('ServerName'))\nif ($is_local = 1)\n  EXEC (@sql);\nELSE\n  EXEC (@sql) AT [$server];"
   },
   {
    "name": "fqdn",
    "label": "Fully Qualified Domain Name",
    "query": "exec dbo.usp_GetAllServerInfo \n\t\t\t\t@servers = '$server',\n\t\t\t\t@output = 'fqdn'"
   },
   {
    "name": "dba_db",
    "label": "DBA Database",
    "query": "declare @sql nvarchar(max);\ndeclare @sql_instance varchar(255);\nset @sql_instance = '$server';\n\nset quoted_identifier off;\nset @sql = \"select top 1 [database] from dbo.instance_details id\nwhere id.sql_instance = @sql_instance\n\";\nset quoted_identifier off;\n\nexec dbo.sp_executesql @sql, N'@sql_instance varchar(255)', @sql_instance;"
   },
   {
    "name": "xevent_collection_time_utc",
    "label": "XEvent Collection Time UTC",
    "query": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\nselect top 1 DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), event_time )\nfrom $xevent_table_name\norder by event_time desc\n\"\nSET QUOTED_IDENTIFIER ON\n\n--IF ('$server' = SERVERPROPERTY('ServerName'))\nif ($is_local = 1)\n  EXEC (@sql);\nELSE\n  EXEC (@sql) AT [$server];"
   },
   { "name": "xevent_view_name", "label": "XEvent View", "query": "${VAR_XEVENT_VIEW_NAME}" },
   { "name": "xevent_table_name", "label": "XEvent Table", "query": "${VAR_XEVENT_TABLE_NAME}" },
   {
    "name": "xevent_queries_table_name",
    "label": "XEvent Queries Table",
    "query": "${VAR_XEVENT_QUERIES_TABLE_NAME}"
   },
   { "name": "grouping_key", "label": "Group By", "query": "Login,Program,Host,Database" },
   { "name": "trend_by", "label": "Trend By", "query": "Hourly,Daily" },
   {
    "name": "hour_of_day",
    "label": "Hour",
    "query": ";with t_hours as (\n\tselect [hour] = 0\n\tunion all\n\tselect [hour] = u.hour+1\n\tfrom t_hours u\n\twhere u.hour < 23\n)\nselect [hour] from t_hours"
   },
   { "name": "login", "label": "Login" },
   { "name": "program", "label": "Program" }
  ]
 },
 "panels": [
  {
   "title": "XEvent - ${trend_by} TREND - CPU - By - {${grouping_key:pipe}}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "XEvent - ${trend_by} TREND - CPU - By - {${grouping_key:pipe}}",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @crlf nchar(2) = nchar(13)+nchar(10);\n\ndeclare @database nvarchar(500) = '$database';\ndeclare @trend_by varchar(20) = '$trend_by'; -- Hour,Day\ndeclare @hour_of_day int = ${hour_of_day};\ndeclare @grouping_key varchar(500) = '${grouping_key:raw}'; --Login,Program,Host,Database\ndeclare @group_by_sql varchar(500) = '';\ndeclare @group_by_metric varchar(500);\ndeclare @login varchar(125) = '$login';\ndeclare @program varchar(500) = '$program';\nset @login = case when ltrim(rtrim(@login)) = '' then null else @login end;\nset @program = case when ltrim(rtrim(@program)) = '' then null else @program end;\n\nset @sql_instance = '$server';\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @database nvarchar(500), @login varchar(125), @program varchar(500), @hour_of_day int';\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nif @grouping_key like '%Login%'\nbegin\n\t\tset @group_by_sql += ', username'\n\t\tset @group_by_metric = case when @group_by_metric is null then 'username' else @group_by_metric +'+'' || ''+username' end;\nend\nif @grouping_key like '%Program%'\nbegin\n\t\tset @group_by_sql += ', client_app_name'\n\t\tset @group_by_metric = case when @group_by_metric is null then 'client_app_name' else @group_by_metric +'+'' || ''+client_app_name' end;\nend\nif @grouping_key like '%Host%'\nbegin\n\t\tset @group_by_sql += ', client_hostname'\n\t\tset @group_by_metric = case when @group_by_metric is null then 'client_hostname' else @group_by_metric +'+'' || ''+client_hostname' end;\nend\nif @grouping_key like '%Database%'\nbegin\n\t\tset @group_by_sql += ', database_name'\n\t\tset @group_by_metric = case when @group_by_metric is null then 'database_name' else @group_by_metric +'+'' || ''+database_name' end;\nend\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor XEvent Dashboard */\nset nocount on;\t\t\t\n\n;with t_xevent_metrics as \n(\n\tselect --top 1000 \n\t\t[time] = \"+(case when @trend_by = 'Daily' \n\t\t\t\t\t\t\t\t\t\tthen 'cast(convert(date,rc.event_time) as datetime)' \n\t\t\t\t\t\t\t\t\t\telse 'dateadd(hour,DATEPART(hour,rc.event_time),cast(convert(date,rc.event_time) as datetime))' \n\t\t\t\t\t\t\t\tend)+@group_by_sql+\" ,cpu_time_ms ,logical_reads ,result\n\tfrom $xevent_table_name rc with (nolock)\n\twhere 1=1\n\tand rc.event_time between DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @start_time_utc) and DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @end_time_utc)\n\t\"+(case when @database is null then '-- ' else '' end)+\"and rc.database_name like ('%'+@database+'%')\n\t\"+(case when @login is null then '-- ' else '' end)+\"and rc.username = @login\n\t\"+(case when @program is null then '-- ' else '' end)+\"and rc.client_app_name = @program\n\t\"+(case when @trend_by = 'Daily' then '-- ' else '' end)+\"and DATEPART(hour,rc.event_time) = @hour_of_day\n)\nselect \t[time] = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), [time]) ,\n\t\t\t\t[metric] = \"+@group_by_metric+\" ,cpu_time_ms = sum(cpu_time_ms) --,logical_reads ,result\nfrom t_xevent_metrics rc\nwhere 1=1\ngroup by [time] \"+@group_by_sql+\"\norder by [time]\n\"\nset quoted_identifier on;\nprint @sql\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @database, @login, @program, @hour_of_day;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @database, @login, @program, @hour_of_day;"
      }
     ]
    }
   ]
  },
  {
   "title": "XEvent - ${trend_by} TREND - Counts - By - {${grouping_key:pipe}}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "XEvent - ${trend_by} TREND - Counts - By - {${grouping_key:pipe}}",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @crlf nchar(2) = nchar(13)+nchar(10);\ndeclare @login varchar(125) = '$login';\ndeclare @program varchar(500) = '$program';\n\ndeclare @database nvarchar(500) = '$database';\ndeclare @trend_by varchar(20) = '$trend_by'; -- Hourly,Daily\ndeclare @hour_of_day int = ${hour_of_day};\ndeclare @grouping_key varchar(500) = '${grouping_key:raw}'; --Login,Program,Host,Database\ndeclare @group_by_sql varchar(500) = '';\ndeclare @group_by_metric varchar(500);\n\nset @sql_instance = '$server';\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\n\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nset @login = case when ltrim(rtrim(@login)) = '' then null else @login end;\nset @program = case when ltrim(rtrim(@program)) = '' then null else @program end;\nif @grouping_key like '%Login%'\nbegin\n\t\tset @group_by_sql += ', username'\n\t\tset @group_by_metric = case when @group_by_metric is null then 'username' else @group_by_metric +'+'' || ''+username' end;\nend\nif @grouping_key like '%Program%'\nbegin\n\t\tset @group_by_sql += ', client_app_name'\n\t\tset @group_by_metric = case when @group_by_metric is null then 'client_app_name' else @group_by_metric +'+'' || ''+client_app_name' end;\nend\nif @grouping_key like '%Host%'\nbegin\n\t\tset @group_by_sql += ', client_hostname'\n\t\tset @group_by_metric = case when @group_by_metric is null then 'client_hostname' else @group_by_metric +'+'' || ''+client_hostname' end;\nend\nif @grouping_key like '%Database%'\nbegin\n\t\tset @group_by_sql += ', database_name'\n\t\tset @group_by_metric = case when @group_by_metric is null then 'database_name' else @group_by_metric +'+'' || ''+database_name' end;\nend\n\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @database nvarchar(500), @login varchar(125), @program varchar(500), @hour_of_day int';\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor Dashboard WhoIsActive - SQL Server Queries - Workload: LongRunningQueries  */\nset nocount on;\t\t\t\n\n;with t_xevent_metrics as \n(\n\tselect --top 1000 \n\t\t[time] = \"+(case when @trend_by = 'Daily' \n\t\t\t\t\t\t\t\t\t\tthen 'cast(convert(date,rc.event_time) as datetime)' \n\t\t\t\t\t\t\t\t\t\telse 'dateadd(hour,DATEPART(hour,rc.event_time),cast(convert(date,rc.event_time) as datetime))' \n\t\t\t\t\t\t\t\tend)+@group_by_sql+\" ,cpu_time_ms ,logical_reads ,result\n\tfrom $xevent_table_name rc with (nolock)\n\twhere 1=1\n\tand rc.event_time between DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @start_time_utc) and DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @end_time_utc)\n\t\"+(case when @database is null then '-- ' else '' end)+\"and rc.database_name like ('%'+@database+'%')\n\t\"+(case when @login is null then '-- ' else '' end)+\"and rc.username = @login\n\t\"+(case when @program is null then '-- ' else '' end)+\"and rc.client_app_name = @program\n\t\"+(case when @trend_by = 'Daily' then '-- ' else '' end)+\"and DATEPART(hour,rc.event_time) = @hour_of_day\n)\nselect \t[time] = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), [time]) ,\n\t\t\t\t[metric] = \"+@group_by_metric+\" ,counts = count(1) -- cpu_time_ms,logical_reads ,result\nfrom t_xevent_metrics rc\nwhere 1=1\ngroup by [time] \"+@group_by_sql+\"\norder by [time]\n\"\nset quoted_identifier on;\nprint @sql\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @database, @login, @program, @hour_of_day;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @database, @login, @program, @hour_of_day;"
    }
   ]
  },
  {
   "title": "XEvent - ${trend_by} TREND - READS - By - {${grouping_key:pipe}}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "XEvent - ${trend_by} TREND - Reads - By - {${grouping_key:pipe}}",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @sql_instance varchar(255);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @crlf nchar(2) = nchar(13)+nchar(10);\n\ndeclare @database nvarchar(500) = '$database';\ndeclare @trend_by varchar(20) = '$trend_by'; -- Hour,Day\ndeclare @hour_of_day int = ${hour_of_day};\ndeclare @grouping_key varchar(500) = '${grouping_key:raw}'; --Login,Program,Host,Database\ndeclare @group_by_sql varchar(500) = '';\ndeclare @group_by_metric varchar(500);\ndeclare @login varchar(125) = '$login';\ndeclare @program varchar(500) = '$program';\nset @login = case when ltrim(rtrim(@login)) = '' then null else @login end;\nset @program = case when ltrim(rtrim(@program)) = '' then null else @program end;\n\nset @sql_instance = '$server';\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @database nvarchar(500), @login varchar(125), @program varchar(500), @hour_of_day int';\nset @database = case when ltrim(rtrim(@database)) = '__All__' then null else @database end;\nif @grouping_key like '%Login%'\nbegin\n\t\tset @group_by_sql += ', username'\n\t\tset @group_by_metric = case when @group_by_metric is null then 'username' else @group_by_metric +'+'' || ''+username' end;\nend\nif @grouping_key like '%Program%'\nbegin\n\t\tset @group_by_sql += ', client_app_name'\n\t\tset @group_by_metric = case when @group_by_metric is null then 'client_app_name' else @group_by_metric +'+'' || ''+client_app_name' end;\nend\nif @grouping_key like '%Host%'\nbegin\n\t\tset @group_by_sql += ', client_hostname'\n\t\tset @group_by_metric = case when @group_by_metric is null then 'client_hostname' else @group_by_metric +'+'' || ''+client_hostname' end;\nend\nif @grouping_key like '%Database%'\nbegin\n\t\tset @group_by_sql += ', database_name'\n\t\tset @group_by_metric = case when @group_by_metric is null then 'database_name' else @group_by_metric +'+'' || ''+database_name' end;\nend\n\nset quoted_identifier off;\nset @sql = \"/* SQLMonitor Dashboard WhoIsActive - SQL Server Queries - Workload: LongRunningQueries  */\nset nocount on;\t\t\t\n\n;with t_xevent_metrics as \n(\n\tselect --top 1000 \n\t\t[time] = \"+(case when @trend_by = 'Daily' \n\t\t\t\t\t\t\t\t\t\tthen 'cast(convert(date,rc.event_time) as datetime)' \n\t\t\t\t\t\t\t\t\t\telse 'dateadd(hour,DATEPART(hour,rc.event_time),cast(convert(date,rc.event_time) as datetime))' \n\t\t\t\t\t\t\t\tend)+@group_by_sql+\" ,cpu_time_ms ,logical_reads ,result\n\tfrom $xevent_table_name rc with (nolock)\n\twhere 1=1\n\tand rc.event_time between DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @start_time_utc) and DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @end_time_utc)\n\t\"+(case when @database is null then '-- ' else '' end)+\"and rc.database_name like ('%'+@database+'%')\n\t\"+(case when @login is null then '-- ' else '' end)+\"and rc.username = @login\n\t\"+(case when @program is null then '-- ' else '' end)+\"and rc.client_app_name = @program\n\t\"+(case when @trend_by = 'Daily' then '-- ' else '' end)+\"and DATEPART(hour,rc.event_time) = @hour_of_day\n)\nselect \t[time] = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), [time]) ,\n\t\t\t\t[metric] = \"+@group_by_metric+\" ,logical_reads_mb = sum(logical_reads)*8/128 --,logical_reads ,result\nfrom t_xevent_metrics rc\nwhere 1=1\ngroup by [time] \"+@group_by_sql+\"\norder by [time]\n\"\nset quoted_identifier on;\nprint @sql\n\n--if (@sql_instance = SERVERPROPERTY('SERVERNAME'))\nif ($is_local = 1)\n  exec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @database, @login, @program, @hour_of_day;\nelse\n  exec [$server].[$dba_db].dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @database, @login, @program, @hour_of_day;"
      }
     ]
    }
   ]
  },
  {
   "title": "Other Dashboards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    { "title": "Other Dashboards", "type": "dashlist", "gridPos": { "h": 20, "w": 24, "x": 0, "y": 4 } }
   ]
  }
 ]
}