{
 "title": "Core Metrics - Trend",
 "description": "Display Workload Details Captured using Extended Events",
 "tags": [
  "mssql",
  "sqlmonitor",
  "XEvents"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "sqlmonitor_datasource", "label": "Data Source", "query": "mssql" },
   {
    "name": "server",
    "label": "Sql Instance",
    "query": "select distinct srvname = sql_instance from dbo.instance_details with (nolock)\nwhere is_available = 1 and is_enabled = 1"
   },
   { "name": "trend_by", "label": "Trend By", "query": "Hourly,Daily" },
   {
    "name": "hour_of_day",
    "label": "Hour",
    "query": ";with t_hours as (\n\tselect [hour] = 0\n\tunion all\n\tselect [hour] = u.hour+1\n\tfrom t_hours u\n\twhere u.hour < 23\n)\nselect [hour] from t_hours"
   },
   {
    "name": "vih_hourly_collection_time",
    "label": "Lastest Date",
    "query": "select coalesce(max(collection_time),getdate()-1)\nfrom dbo.all_server_volatile_info_history_hourly hh;"
   },
   { "name": "percentile", "label": "Percentile", "query": "p993,p99,p98,p95,p50" },
   { "name": "max_servers_to_display", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "Core Metrics - ${trend_by} TREND - CPU - Max {$max_servers_to_display} Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Core Metrics - ${trend_by} TREND - OS CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @servers varchar(8000);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @crlf nchar(2) = nchar(13)+nchar(10);\n\ndeclare @max_servers_to_display int = $max_servers_to_display;\ndeclare @parameter_servers_count int = 1;\ndeclare @trend_by varchar(20) = '$trend_by'; -- Hourly,Daily\ndeclare @percentile varchar(20) = '$percentile';\ndeclare @hour_of_day int = ${hour_of_day};\ndeclare @vih_hourly_collection_time datetime2 = '${vih_hourly_collection_time:date:iso}';\ndeclare @group_by_sql varchar(500) = '';\ndeclare @group_by_metric varchar(500);\n\nset @servers = '${server:raw}';\nset @parameter_servers_count = len(@servers)-len(replace(@servers,',','')) + 1;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\n\n\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @hour_of_day int, @servers varchar(8000), @max_servers_to_display int, @vih_hourly_collection_time datetime2';\n\n\nset quoted_identifier off;\nset @sql = \"/* $__dashboard */\nset nocount on;\t\t\t\n\n;with t_history_hourly as \n(\n  select  distinct\n          [time] = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), \"+(case when @trend_by = 'Daily' \n                          then 'cast(convert(date,hh.collection_time) as datetime)' \n                          else 'hh.collection_time' \n                      end)+\"),\n          \"+(case when @parameter_servers_count = 1 then '--' else '' end)+\"hh.srv_name, \n          \"+(case when @trend_by = 'Hourly' then '--' else '' end)+\"/*\n            \"+(case when @percentile = 'p993' then '' else '--' end)+\"hh.os_cpu__p993\n            \"+(case when @percentile = 'p99' then '' else '--' end)+\"hh.os_cpu__p99\n            \"+(case when @percentile = 'p98' then '' else '--' end)+\"hh.os_cpu__p98\n            \"+(case when @percentile = 'p95' then '' else '--' end)+\"hh.os_cpu__p95\n            \"+(case when @percentile = 'p50' then '' else '--' end)+\"hh.os_cpu__p50\n          \"+(case when @trend_by = 'Hourly' then '--' else '' end)+\"*/\n          \"+(case when @trend_by = 'Daily' then '--' else '' end)+\"/*\n            \"+(case when @percentile = 'p993' then '' else '--' end)+\"os_cpu__p993 = PERCENTILE_CONT(99.3*0.01) WITHIN GROUP (ORDER BY hh.os_cpu__p993) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p99' then '' else '--' end)+\"os_cpu__p99 = PERCENTILE_CONT(99*0.01) WITHIN GROUP (ORDER BY hh.os_cpu__p99) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p98' then '' else '--' end)+\"os_cpu__p98 = PERCENTILE_CONT(98*0.01) WITHIN GROUP (ORDER BY hh.os_cpu__p98) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p95' then '' else '--' end)+\"os_cpu__p95 = PERCENTILE_CONT(95*0.01) WITHIN GROUP (ORDER BY hh.os_cpu__p95) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p50' then '' else '--' end)+\"os_cpu__p50 = PERCENTILE_CONT(50*0.01) WITHIN GROUP (ORDER BY hh.os_cpu__p50) OVER (PARTITION BY cast(collection_time as date), srv_name)\n          \"+(case when @trend_by = 'Daily' then '--' else '' end)+\"*/\n  from dbo.all_server_volatile_info_history_hourly hh\n  where 1=1\n  and exists (select 1/0 from dbo.instance_details id where id.is_enabled = 1 and id.is_alias = 0 and id.sql_instance = hh.srv_name)\n  and hh.srv_name in (select ss.csv_substring from dbo.fn_split_string(@servers,',') ss where ss.srno <= @max_servers_to_display)\n  and hh.collection_time >= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @start_time_utc)\n  and hh.collection_time <= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @end_time_utc)\n  \"+(case when @trend_by = 'Hourly' then '' else '--' end)+\"and datepart(hour,collection_time) = @hour_of_day\n),\nt_history_regular as (\n  select  [time] = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), \"+(case when @trend_by = 'Daily' \n                          then 'cast(convert(date,hh.collection_time) as datetime)' \n                          else 'dateadd(hour,DATEPART(hour,hh.collection_time),cast(convert(date,hh.collection_time) as datetime))'\n                      end)+\"),\n          hh.srv_name, \n          hh.os_cpu\n  from dbo.all_server_volatile_info_history hh\n  where 1=1\n  and exists (select 1/0 from dbo.instance_details id where id.is_enabled = 1 and id.is_alias = 0 and id.sql_instance = hh.srv_name)\n  and hh.srv_name in (select ss.csv_substring from dbo.fn_split_string(@servers,',') ss where ss.srno <= @max_servers_to_display)\n  and hh.collection_time >= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @start_time_utc)\n  and hh.collection_time <= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @end_time_utc)\n  and hh.collection_time > @vih_hourly_collection_time\n  \"+(case when @trend_by = 'Hourly' then '' else '--' end)+\"and datepart(hour,collection_time) = @hour_of_day\n)\n,t_history_regular_to_trendby as (\n  select distinct \n          [time],\n          \"+(case when @parameter_servers_count = 1 then '--' else '' end)+\"hh.srv_name,\n          \"+(case when @percentile = 'p50' then '' else '--' end)+\"os_cpu__p50 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(50*0.01) WITHIN GROUP (ORDER BY os_cpu) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p95' then '' else '--' end)+\"os_cpu__p95 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(95*0.01) WITHIN GROUP (ORDER BY os_cpu) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p98' then '' else '--' end)+\"os_cpu__p98 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(98*0.01) WITHIN GROUP (ORDER BY os_cpu) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p99' then '' else '--' end)+\"os_cpu__p99 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(99*0.01) WITHIN GROUP (ORDER BY os_cpu) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p993' then '' else '--' end)+\"os_cpu__p993 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(99.3*0.01) WITHIN GROUP (ORDER BY os_cpu) OVER (PARTITION BY [time], srv_name))\n\n  from t_history_regular hh\n  where 1=1\n)\n,t_history as (\n  select * from t_history_hourly\n  union all\n  select * from t_history_regular_to_trendby\n)\nselect *\nfrom t_history\norder by [time]\n\"\nset quoted_identifier on;\nprint @sql\n\nexec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @hour_of_day, @servers, @max_servers_to_display, @vih_hourly_collection_time;"
      }
     ]
    },
    {
     "title": "Core Metrics - ${trend_by} TREND - SQL CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @servers varchar(8000);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @crlf nchar(2) = nchar(13)+nchar(10);\n\ndeclare @max_servers_to_display int = $max_servers_to_display;\ndeclare @parameter_servers_count int = 1;\ndeclare @trend_by varchar(20) = '$trend_by'; -- Hourly,Daily\ndeclare @percentile varchar(20) = '$percentile';\ndeclare @hour_of_day int = ${hour_of_day};\ndeclare @vih_hourly_collection_time datetime2 = '${vih_hourly_collection_time:date:iso}';\ndeclare @group_by_sql varchar(500) = '';\ndeclare @group_by_metric varchar(500);\n\nset @servers = '${server:raw}';\nset @parameter_servers_count = len(@servers)-len(replace(@servers,',','')) + 1;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\n\n\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @hour_of_day int, @servers varchar(8000), @max_servers_to_display int, @vih_hourly_collection_time datetime2';\n\n\nset quoted_identifier off;\nset @sql = \"/* $__dashboard */\nset nocount on;\t\t\t\n\n;with t_history_hourly as \n(\n  select  distinct\n          [time] = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), \"+(case when @trend_by = 'Daily' \n                          then 'cast(convert(date,hh.collection_time) as datetime)' \n                          else 'hh.collection_time' \n                      end)+\"),\n          \"+(case when @parameter_servers_count = 1 then '--' else '' end)+\"hh.srv_name, \n          \"+(case when @trend_by = 'Hourly' then '--' else '' end)+\"/*\n            \"+(case when @percentile = 'p993' then '' else '--' end)+\"hh.sql_cpu__p993\n            \"+(case when @percentile = 'p99' then '' else '--' end)+\"hh.sql_cpu__p99\n            \"+(case when @percentile = 'p98' then '' else '--' end)+\"hh.sql_cpu__p98\n            \"+(case when @percentile = 'p95' then '' else '--' end)+\"hh.sql_cpu__p95\n            \"+(case when @percentile = 'p50' then '' else '--' end)+\"hh.sql_cpu__p50\n          \"+(case when @trend_by = 'Hourly' then '--' else '' end)+\"*/\n          \"+(case when @trend_by = 'Daily' then '--' else '' end)+\"/*\n            \"+(case when @percentile = 'p993' then '' else '--' end)+\"sql_cpu__p993 = PERCENTILE_CONT(99.3*0.01) WITHIN GROUP (ORDER BY hh.sql_cpu__p993) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p99' then '' else '--' end)+\"sql_cpu__p99 = PERCENTILE_CONT(99*0.01) WITHIN GROUP (ORDER BY hh.sql_cpu__p99) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p98' then '' else '--' end)+\"sql_cpu__p98 = PERCENTILE_CONT(98*0.01) WITHIN GROUP (ORDER BY hh.sql_cpu__p98) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p95' then '' else '--' end)+\"sql_cpu__p95 = PERCENTILE_CONT(95*0.01) WITHIN GROUP (ORDER BY hh.sql_cpu__p95) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p50' then '' else '--' end)+\"sql_cpu__p50 = PERCENTILE_CONT(50*0.01) WITHIN GROUP (ORDER BY hh.sql_cpu__p50) OVER (PARTITION BY cast(collection_time as date), srv_name)\n          \"+(case when @trend_by = 'Daily' then '--' else '' end)+\"*/\n  from dbo.all_server_volatile_info_history_hourly hh\n  where 1=1\n  and exists (select 1/0 from dbo.instance_details id where id.is_enabled = 1 and id.is_alias = 0 and id.sql_instance = hh.srv_name)\n  and hh.srv_name in (select ss.csv_substring from dbo.fn_split_string(@servers,',') ss where ss.srno <= @max_servers_to_display)\n  and hh.collection_time >= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @start_time_utc)\n  and hh.collection_time <= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @end_time_utc)\n  \"+(case when @trend_by = 'Hourly' then '' else '--' end)+\"and datepart(hour,collection_time) = @hour_of_day\n),\nt_history_regular as (\n  select  [time] = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), \"+(case when @trend_by = 'Daily' \n                          then 'cast(convert(date,hh.collection_time) as datetime)' \n                          else 'dateadd(hour,DATEPART(hour,hh.collection_time),cast(convert(date,hh.collection_time) as datetime))'\n                      end)+\"),\n          hh.srv_name, \n          hh.sql_cpu\n  from dbo.all_server_volatile_info_history hh\n  where 1=1\n  and exists (select 1/0 from dbo.instance_details id where id.is_enabled = 1 and id.is_alias = 0 and id.sql_instance = hh.srv_name)\n  and hh.srv_name in (select ss.csv_substring from dbo.fn_split_string(@servers,',') ss where ss.srno <= @max_servers_to_display)\n  and hh.collection_time >= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @start_time_utc)\n  and hh.collection_time <= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @end_time_utc)\n  and hh.collection_time > @vih_hourly_collection_time\n  \"+(case when @trend_by = 'Hourly' then '' else '--' end)+\"and datepart(hour,collection_time) = @hour_of_day\n)\n,t_history_regular_to_trendby as (\n  select distinct \n          [time],\n          \"+(case when @parameter_servers_count = 1 then '--' else '' end)+\"hh.srv_name,\n          \"+(case when @percentile = 'p50' then '' else '--' end)+\"sql_cpu__p50 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(50*0.01) WITHIN GROUP (ORDER BY sql_cpu) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p95' then '' else '--' end)+\"sql_cpu__p95 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(95*0.01) WITHIN GROUP (ORDER BY sql_cpu) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p98' then '' else '--' end)+\"sql_cpu__p98 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(98*0.01) WITHIN GROUP (ORDER BY sql_cpu) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p99' then '' else '--' end)+\"sql_cpu__p99 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(99*0.01) WITHIN GROUP (ORDER BY sql_cpu) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p993' then '' else '--' end)+\"sql_cpu__p993 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(99.3*0.01) WITHIN GROUP (ORDER BY sql_cpu) OVER (PARTITION BY [time], srv_name))\n\n  from t_history_regular hh\n  where 1=1\n)\n,t_history as (\n  select * from t_history_hourly\n  union all\n  select * from t_history_regular_to_trendby\n)\nselect *\nfrom t_history\norder by [time]\n\"\nset quoted_identifier on;\nprint @sql\n\nexec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @hour_of_day, @servers, @max_servers_to_display, @vih_hourly_collection_time;"
      }
     ]
    }
   ]
  },
  {
   "title": "Core Metrics - ${trend_by} TREND - Disk Latency - Max {$max_servers_to_display} Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Core Metrics - ${trend_by} TREND - Disk Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @servers varchar(8000);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @crlf nchar(2) = nchar(13)+nchar(10);\n\ndeclare @max_servers_to_display int = $max_servers_to_display;\ndeclare @parameter_servers_count int = 1;\ndeclare @trend_by varchar(20) = '$trend_by'; -- Hourly,Daily\ndeclare @percentile varchar(20) = '$percentile';\ndeclare @hour_of_day int = ${hour_of_day};\ndeclare @vih_hourly_collection_time datetime2 = '${vih_hourly_collection_time:date:iso}';\ndeclare @group_by_sql varchar(500) = '';\ndeclare @group_by_metric varchar(500);\n\nset @servers = '${server:raw}';\nset @parameter_servers_count = len(@servers)-len(replace(@servers,',','')) + 1;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\n\n\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @hour_of_day int, @servers varchar(8000), @max_servers_to_display int, @vih_hourly_collection_time datetime2';\n\n\nset quoted_identifier off;\nset @sql = \"/* $__dashboard */\nset nocount on;\t\t\t\n\n;with t_history_hourly as \n(\n  select  distinct\n          [time] = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), \"+(case when @trend_by = 'Daily' \n                          then 'cast(convert(date,hh.collection_time) as datetime)' \n                          else 'hh.collection_time' \n                      end)+\"),\n          \"+(case when @parameter_servers_count = 1 then '--' else '' end)+\"hh.srv_name, \n          \"+(case when @trend_by = 'Hourly' then '--' else '' end)+\"/*\n            \"+(case when @percentile = 'p993' then '' else '--' end)+\"hh.avg_disk_latency_ms__p993\n            \"+(case when @percentile = 'p99' then '' else '--' end)+\"hh.avg_disk_latency_ms__p99\n            \"+(case when @percentile = 'p98' then '' else '--' end)+\"hh.avg_disk_latency_ms__p98\n            \"+(case when @percentile = 'p95' then '' else '--' end)+\"hh.avg_disk_latency_ms__p95\n            \"+(case when @percentile = 'p50' then '' else '--' end)+\"hh.avg_disk_latency_ms__p50\n          \"+(case when @trend_by = 'Hourly' then '--' else '' end)+\"*/\n          \"+(case when @trend_by = 'Daily' then '--' else '' end)+\"/*\n            \"+(case when @percentile = 'p993' then '' else '--' end)+\"avg_disk_latency_ms__p993 = PERCENTILE_CONT(99.3*0.01) WITHIN GROUP (ORDER BY hh.avg_disk_latency_ms__p993) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p99' then '' else '--' end)+\"avg_disk_latency_ms__p99 = PERCENTILE_CONT(99*0.01) WITHIN GROUP (ORDER BY hh.avg_disk_latency_ms__p99) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p98' then '' else '--' end)+\"avg_disk_latency_ms__p98 = PERCENTILE_CONT(98*0.01) WITHIN GROUP (ORDER BY hh.avg_disk_latency_ms__p98) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p95' then '' else '--' end)+\"avg_disk_latency_ms__p95 = PERCENTILE_CONT(95*0.01) WITHIN GROUP (ORDER BY hh.avg_disk_latency_ms__p95) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p50' then '' else '--' end)+\"avg_disk_latency_ms__p50 = PERCENTILE_CONT(50*0.01) WITHIN GROUP (ORDER BY hh.avg_disk_latency_ms__p50) OVER (PARTITION BY cast(collection_time as date), srv_name)\n          \"+(case when @trend_by = 'Daily' then '--' else '' end)+\"*/\n  from dbo.all_server_volatile_info_history_hourly hh\n  where 1=1\n  and exists (select 1/0 from dbo.instance_details id where id.is_enabled = 1 and id.is_alias = 0 and id.sql_instance = hh.srv_name)\n  and hh.srv_name in (select ss.csv_substring from dbo.fn_split_string(@servers,',') ss where ss.srno <= @max_servers_to_display)\n  and hh.collection_time >= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @start_time_utc)\n  and hh.collection_time <= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @end_time_utc)\n  \"+(case when @trend_by = 'Hourly' then '' else '--' end)+\"and datepart(hour,collection_time) = @hour_of_day\n),\nt_history_regular as (\n  select  [time] = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), \"+(case when @trend_by = 'Daily' \n                          then 'cast(convert(date,hh.collection_time) as datetime)' \n                          else 'dateadd(hour,DATEPART(hour,hh.collection_time),cast(convert(date,hh.collection_time) as datetime))'\n                      end)+\"),\n          hh.srv_name, \n          hh.avg_disk_latency_ms\n  from dbo.all_server_volatile_info_history hh\n  where 1=1\n  and exists (select 1/0 from dbo.instance_details id where id.is_enabled = 1 and id.is_alias = 0 and id.sql_instance = hh.srv_name)\n  and hh.srv_name in (select ss.csv_substring from dbo.fn_split_string(@servers,',') ss where ss.srno <= @max_servers_to_display)\n  and hh.collection_time >= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @start_time_utc)\n  and hh.collection_time <= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @end_time_utc)\n  and hh.collection_time > @vih_hourly_collection_time\n  \"+(case when @trend_by = 'Hourly' then '' else '--' end)+\"and datepart(hour,collection_time) = @hour_of_day\n)\n,t_history_regular_to_trendby as (\n  select distinct \n          [time],\n          \"+(case when @parameter_servers_count = 1 then '--' else '' end)+\"hh.srv_name,\n          \"+(case when @percentile = 'p50' then '' else '--' end)+\"avg_disk_latency_ms__p50 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(50*0.01) WITHIN GROUP (ORDER BY avg_disk_latency_ms) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p95' then '' else '--' end)+\"avg_disk_latency_ms__p95 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(95*0.01) WITHIN GROUP (ORDER BY avg_disk_latency_ms) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p98' then '' else '--' end)+\"avg_disk_latency_ms__p98 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(98*0.01) WITHIN GROUP (ORDER BY avg_disk_latency_ms) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p99' then '' else '--' end)+\"avg_disk_latency_ms__p99 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(99*0.01) WITHIN GROUP (ORDER BY avg_disk_latency_ms) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p993' then '' else '--' end)+\"avg_disk_latency_ms__p993 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(99.3*0.01) WITHIN GROUP (ORDER BY avg_disk_latency_ms) OVER (PARTITION BY [time], srv_name))\n\n  from t_history_regular hh\n  where 1=1\n)\n,t_history as (\n  select * from t_history_hourly\n  union all\n  select * from t_history_regular_to_trendby\n)\nselect *\nfrom t_history\norder by [time]\n\"\nset quoted_identifier on;\nprint @sql\n\nexec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @hour_of_day, @servers, @max_servers_to_display, @vih_hourly_collection_time;"
      }
     ]
    }
   ]
  },
  {
   "title": "Core Metrics - ${trend_by} TREND - Requests - Max {$max_servers_to_display} Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Core Metrics - ${trend_by} TREND - Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @servers varchar(8000);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @crlf nchar(2) = nchar(13)+nchar(10);\n\ndeclare @max_servers_to_display int = $max_servers_to_display;\ndeclare @parameter_servers_count int = 1;\ndeclare @trend_by varchar(20) = '$trend_by'; -- Hourly,Daily\ndeclare @percentile varchar(20) = '$percentile';\ndeclare @hour_of_day int = ${hour_of_day};\ndeclare @vih_hourly_collection_time datetime2 = '${vih_hourly_collection_time:date:iso}';\ndeclare @group_by_sql varchar(500) = '';\ndeclare @group_by_metric varchar(500);\n\nset @servers = '${server:raw}';\nset @parameter_servers_count = len(@servers)-len(replace(@servers,',','')) + 1;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\n\n\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @hour_of_day int, @servers varchar(8000), @max_servers_to_display int, @vih_hourly_collection_time datetime2';\n\n\nset quoted_identifier off;\nset @sql = \"/* $__dashboard */\nset nocount on;\t\t\t\n\n;with t_history_hourly as \n(\n  select  distinct\n          [time] = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), \"+(case when @trend_by = 'Daily' \n                          then 'cast(convert(date,hh.collection_time) as datetime)' \n                          else 'hh.collection_time' \n                      end)+\"),\n          \"+(case when @parameter_servers_count = 1 then '--' else '' end)+\"hh.srv_name, \n          \"+(case when @trend_by = 'Hourly' then '--' else '' end)+\"/*\n            \"+(case when @percentile = 'p993' then '' else '--' end)+\"hh.active_requests_count__p993\n            \"+(case when @percentile = 'p99' then '' else '--' end)+\"hh.active_requests_count__p99\n            \"+(case when @percentile = 'p98' then '' else '--' end)+\"hh.active_requests_count__p98\n            \"+(case when @percentile = 'p95' then '' else '--' end)+\"hh.active_requests_count__p95\n            \"+(case when @percentile = 'p50' then '' else '--' end)+\"hh.active_requests_count__p50\n          \"+(case when @trend_by = 'Hourly' then '--' else '' end)+\"*/\n          \"+(case when @trend_by = 'Daily' then '--' else '' end)+\"/*\n            \"+(case when @percentile = 'p993' then '' else '--' end)+\"active_requests_count__p993 = PERCENTILE_CONT(99.3*0.01) WITHIN GROUP (ORDER BY hh.active_requests_count__p993) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p99' then '' else '--' end)+\"active_requests_count__p99 = PERCENTILE_CONT(99*0.01) WITHIN GROUP (ORDER BY hh.active_requests_count__p99) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p98' then '' else '--' end)+\"active_requests_count__p98 = PERCENTILE_CONT(98*0.01) WITHIN GROUP (ORDER BY hh.active_requests_count__p98) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p95' then '' else '--' end)+\"active_requests_count__p95 = PERCENTILE_CONT(95*0.01) WITHIN GROUP (ORDER BY hh.active_requests_count__p95) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p50' then '' else '--' end)+\"active_requests_count__p50 = PERCENTILE_CONT(50*0.01) WITHIN GROUP (ORDER BY hh.active_requests_count__p50) OVER (PARTITION BY cast(collection_time as date), srv_name)\n          \"+(case when @trend_by = 'Daily' then '--' else '' end)+\"*/\n  from dbo.all_server_volatile_info_history_hourly hh\n  where 1=1\n  and exists (select 1/0 from dbo.instance_details id where id.is_enabled = 1 and id.is_alias = 0 and id.sql_instance = hh.srv_name)\n  and hh.srv_name in (select ss.csv_substring from dbo.fn_split_string(@servers,',') ss where ss.srno <= @max_servers_to_display)\n  and hh.collection_time >= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @start_time_utc)\n  and hh.collection_time <= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @end_time_utc)\n  \"+(case when @trend_by = 'Hourly' then '' else '--' end)+\"and datepart(hour,collection_time) = @hour_of_day\n),\nt_history_regular as (\n  select  [time] = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), \"+(case when @trend_by = 'Daily' \n                          then 'cast(convert(date,hh.collection_time) as datetime)' \n                          else 'dateadd(hour,DATEPART(hour,hh.collection_time),cast(convert(date,hh.collection_time) as datetime))'\n                      end)+\"),\n          hh.srv_name, \n          hh.active_requests_count\n  from dbo.all_server_volatile_info_history hh\n  where 1=1\n  and exists (select 1/0 from dbo.instance_details id where id.is_enabled = 1 and id.is_alias = 0 and id.sql_instance = hh.srv_name)\n  and hh.srv_name in (select ss.csv_substring from dbo.fn_split_string(@servers,',') ss where ss.srno <= @max_servers_to_display)\n  and hh.collection_time >= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @start_time_utc)\n  and hh.collection_time <= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @end_time_utc)\n  and hh.collection_time > @vih_hourly_collection_time\n  \"+(case when @trend_by = 'Hourly' then '' else '--' end)+\"and datepart(hour,collection_time) = @hour_of_day\n)\n,t_history_regular_to_trendby as (\n  select distinct \n          [time],\n          \"+(case when @parameter_servers_count = 1 then '--' else '' end)+\"hh.srv_name,\n          \"+(case when @percentile = 'p50' then '' else '--' end)+\"active_requests_count__p50 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(50*0.01) WITHIN GROUP (ORDER BY active_requests_count) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p95' then '' else '--' end)+\"active_requests_count__p95 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(95*0.01) WITHIN GROUP (ORDER BY active_requests_count) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p98' then '' else '--' end)+\"active_requests_count__p98 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(98*0.01) WITHIN GROUP (ORDER BY active_requests_count) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p99' then '' else '--' end)+\"active_requests_count__p99 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(99*0.01) WITHIN GROUP (ORDER BY active_requests_count) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p993' then '' else '--' end)+\"active_requests_count__p993 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(99.3*0.01) WITHIN GROUP (ORDER BY active_requests_count) OVER (PARTITION BY [time], srv_name))\n\n  from t_history_regular hh\n  where 1=1\n)\n,t_history as (\n  select * from t_history_hourly\n  union all\n  select * from t_history_regular_to_trendby\n)\nselect *\nfrom t_history\norder by [time]\n\"\nset quoted_identifier on;\nprint @sql\n\nexec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @hour_of_day, @servers, @max_servers_to_display, @vih_hourly_collection_time;"
      }
     ]
    }
   ]
  },
  {
   "title": "Core Metrics - ${trend_by} TREND - Available Memory - Max {$max_servers_to_display} Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Core Metrics - ${trend_by} TREND - Available Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @servers varchar(8000);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @crlf nchar(2) = nchar(13)+nchar(10);\n\ndeclare @max_servers_to_display int = $max_servers_to_display;\ndeclare @parameter_servers_count int = 1;\ndeclare @trend_by varchar(20) = '$trend_by'; -- Hourly,Daily\ndeclare @percentile varchar(20) = '$percentile';\ndeclare @hour_of_day int = ${hour_of_day};\ndeclare @vih_hourly_collection_time datetime2 = '${vih_hourly_collection_time:date:iso}';\ndeclare @group_by_sql varchar(500) = '';\ndeclare @group_by_metric varchar(500);\n\nset @servers = '${server:raw}';\nset @parameter_servers_count = len(@servers)-len(replace(@servers,',','')) + 1;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\n\n\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @hour_of_day int, @servers varchar(8000), @max_servers_to_display int, @vih_hourly_collection_time datetime2';\n\n\nset quoted_identifier off;\nset @sql = \"/* $__dashboard */\nset nocount on;\t\t\t\n\n;with t_history_hourly as \n(\n  select  distinct\n          [time] = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), \"+(case when @trend_by = 'Daily' \n                          then 'cast(convert(date,hh.collection_time) as datetime)' \n                          else 'hh.collection_time' \n                      end)+\"),\n          \"+(case when @parameter_servers_count = 1 then '--' else '' end)+\"hh.srv_name, \n          \"+(case when @trend_by = 'Hourly' then '--' else '' end)+\"/*\n            \"+(case when @percentile = 'p993' then '' else '--' end)+\"hh.available_physical_memory_kb__p993\n            \"+(case when @percentile = 'p99' then '' else '--' end)+\"hh.available_physical_memory_kb__p99\n            \"+(case when @percentile = 'p98' then '' else '--' end)+\"hh.available_physical_memory_kb__p98\n            \"+(case when @percentile = 'p95' then '' else '--' end)+\"hh.available_physical_memory_kb__p95\n            \"+(case when @percentile = 'p50' then '' else '--' end)+\"hh.available_physical_memory_kb__p50\n          \"+(case when @trend_by = 'Hourly' then '--' else '' end)+\"*/\n          \"+(case when @trend_by = 'Daily' then '--' else '' end)+\"/*\n            \"+(case when @percentile = 'p993' then '' else '--' end)+\"available_physical_memory_kb__p993 = PERCENTILE_CONT(99.3*0.01) WITHIN GROUP (ORDER BY hh.available_physical_memory_kb__p993 desc) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p99' then '' else '--' end)+\"available_physical_memory_kb__p99 = PERCENTILE_CONT(99*0.01) WITHIN GROUP (ORDER BY hh.available_physical_memory_kb__p99 desc) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p98' then '' else '--' end)+\"available_physical_memory_kb__p98 = PERCENTILE_CONT(98*0.01) WITHIN GROUP (ORDER BY hh.available_physical_memory_kb__p98 desc) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p95' then '' else '--' end)+\"available_physical_memory_kb__p95 = PERCENTILE_CONT(95*0.01) WITHIN GROUP (ORDER BY hh.available_physical_memory_kb__p95 desc) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p50' then '' else '--' end)+\"available_physical_memory_kb__p50 = PERCENTILE_CONT(50*0.01) WITHIN GROUP (ORDER BY hh.available_physical_memory_kb__p50 desc) OVER (PARTITION BY cast(collection_time as date), srv_name)\n          \"+(case when @trend_by = 'Daily' then '--' else '' end)+\"*/\n  from dbo.all_server_volatile_info_history_hourly hh\n  where 1=1\n  and exists (select 1/0 from dbo.instance_details id where id.is_enabled = 1 and id.is_alias = 0 and id.sql_instance = hh.srv_name)\n  and hh.srv_name in (select ss.csv_substring from dbo.fn_split_string(@servers,',') ss where ss.srno <= @max_servers_to_display)\n  and hh.collection_time >= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @start_time_utc)\n  and hh.collection_time <= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @end_time_utc)\n  \"+(case when @trend_by = 'Hourly' then '' else '--' end)+\"and datepart(hour,collection_time) = @hour_of_day\n),\nt_history_regular as (\n  select  [time] = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), \"+(case when @trend_by = 'Daily' \n                          then 'cast(convert(date,hh.collection_time) as datetime)' \n                          else 'dateadd(hour,DATEPART(hour,hh.collection_time),cast(convert(date,hh.collection_time) as datetime))'\n                      end)+\"),\n          hh.srv_name, \n          hh.available_physical_memory_kb\n  from dbo.all_server_volatile_info_history hh\n  where 1=1\n  and exists (select 1/0 from dbo.instance_details id where id.is_enabled = 1 and id.is_alias = 0 and id.sql_instance = hh.srv_name)\n  and hh.srv_name in (select ss.csv_substring from dbo.fn_split_string(@servers,',') ss where ss.srno <= @max_servers_to_display)\n  and hh.collection_time >= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @start_time_utc)\n  and hh.collection_time <= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @end_time_utc)\n  and hh.collection_time > @vih_hourly_collection_time\n  \"+(case when @trend_by = 'Hourly' then '' else '--' end)+\"and datepart(hour,collection_time) = @hour_of_day\n)\n,t_history_regular_to_trendby as (\n  select distinct \n          [time],\n          \"+(case when @parameter_servers_count = 1 then '--' else '' end)+\"hh.srv_name,\n          \"+(case when @percentile = 'p50' then '' else '--' end)+\"available_physical_memory_kb__p50 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(50*0.01) WITHIN GROUP (ORDER BY available_physical_memory_kb desc) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p95' then '' else '--' end)+\"available_physical_memory_kb__p95 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(95*0.01) WITHIN GROUP (ORDER BY available_physical_memory_kb desc) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p98' then '' else '--' end)+\"available_physical_memory_kb__p98 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(98*0.01) WITHIN GROUP (ORDER BY available_physical_memory_kb desc) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p99' then '' else '--' end)+\"available_physical_memory_kb__p99 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(99*0.01) WITHIN GROUP (ORDER BY available_physical_memory_kb desc) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p993' then '' else '--' end)+\"available_physical_memory_kb__p993 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(99.3*0.01) WITHIN GROUP (ORDER BY available_physical_memory_kb desc) OVER (PARTITION BY [time], srv_name))\n\n  from t_history_regular hh\n  where 1=1\n)\n,t_history as (\n  select * from t_history_hourly\n  union all\n  select * from t_history_regular_to_trendby\n)\nselect *\nfrom t_history\norder by [time]\n\"\nset quoted_identifier on;\nprint @sql\n\nexec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @hour_of_day, @servers, @max_servers_to_display, @vih_hourly_collection_time;"
      }
     ]
    }
   ]
  },
  {
   "title": "Core Metrics - ${trend_by} TREND - Connections - Max {$max_servers_to_display} Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Core Metrics - ${trend_by} TREND - Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "declare @sql nvarchar(max);\ndeclare @params nvarchar(max);\ndeclare @servers varchar(8000);\ndeclare @start_time_utc datetime2;\ndeclare @end_time_utc datetime2;\ndeclare @crlf nchar(2) = nchar(13)+nchar(10);\n\ndeclare @max_servers_to_display int = $max_servers_to_display;\ndeclare @parameter_servers_count int = 1;\ndeclare @trend_by varchar(20) = '$trend_by'; -- Hourly,Daily\ndeclare @percentile varchar(20) = '$percentile';\ndeclare @hour_of_day int = ${hour_of_day};\ndeclare @vih_hourly_collection_time datetime2 = '${vih_hourly_collection_time:date:iso}';\ndeclare @group_by_sql varchar(500) = '';\ndeclare @group_by_metric varchar(500);\n\nset @servers = '${server:raw}';\nset @parameter_servers_count = len(@servers)-len(replace(@servers,',','')) + 1;\nset @start_time_utc = $__timeFrom();\nset @end_time_utc = $__timeTo();\n\n\nset @params = N'@start_time_utc datetime2, @end_time_utc datetime2, @hour_of_day int, @servers varchar(8000), @max_servers_to_display int, @vih_hourly_collection_time datetime2';\n\n\nset quoted_identifier off;\nset @sql = \"/* $__dashboard */\nset nocount on;\t\t\t\n\n;with t_history_hourly as \n(\n  select  distinct\n          [time] = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), \"+(case when @trend_by = 'Daily' \n                          then 'cast(convert(date,hh.collection_time) as datetime)' \n                          else 'hh.collection_time' \n                      end)+\"),\n          \"+(case when @parameter_servers_count = 1 then '--' else '' end)+\"hh.srv_name, \n          \"+(case when @trend_by = 'Hourly' then '--' else '' end)+\"/*\n            \"+(case when @percentile = 'p993' then '' else '--' end)+\"hh.connection_count__p993\n            \"+(case when @percentile = 'p99' then '' else '--' end)+\"hh.connection_count__p99\n            \"+(case when @percentile = 'p98' then '' else '--' end)+\"hh.connection_count__p98\n            \"+(case when @percentile = 'p95' then '' else '--' end)+\"hh.connection_count__p95\n            \"+(case when @percentile = 'p50' then '' else '--' end)+\"hh.connection_count__p50\n          \"+(case when @trend_by = 'Hourly' then '--' else '' end)+\"*/\n          \"+(case when @trend_by = 'Daily' then '--' else '' end)+\"/*\n            \"+(case when @percentile = 'p993' then '' else '--' end)+\"connection_count__p993 = PERCENTILE_CONT(99.3*0.01) WITHIN GROUP (ORDER BY hh.connection_count__p993) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p99' then '' else '--' end)+\"connection_count__p99 = PERCENTILE_CONT(99*0.01) WITHIN GROUP (ORDER BY hh.connection_count__p99) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p98' then '' else '--' end)+\"connection_count__p98 = PERCENTILE_CONT(98*0.01) WITHIN GROUP (ORDER BY hh.connection_count__p98) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p95' then '' else '--' end)+\"connection_count__p95 = PERCENTILE_CONT(95*0.01) WITHIN GROUP (ORDER BY hh.connection_count__p95) OVER (PARTITION BY cast(collection_time as date), srv_name)\n            \"+(case when @percentile = 'p50' then '' else '--' end)+\"connection_count__p50 = PERCENTILE_CONT(50*0.01) WITHIN GROUP (ORDER BY hh.connection_count__p50) OVER (PARTITION BY cast(collection_time as date), srv_name)\n          \"+(case when @trend_by = 'Daily' then '--' else '' end)+\"*/\n  from dbo.all_server_volatile_info_history_hourly hh\n  where 1=1\n  and exists (select 1/0 from dbo.instance_details id where id.is_enabled = 1 and id.is_alias = 0 and id.sql_instance = hh.srv_name)\n  and hh.srv_name in (select ss.csv_substring from dbo.fn_split_string(@servers,',') ss where ss.srno <= @max_servers_to_display)\n  and hh.collection_time >= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @start_time_utc)\n  and hh.collection_time <= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @end_time_utc)\n  \"+(case when @trend_by = 'Hourly' then '' else '--' end)+\"and datepart(hour,collection_time) = @hour_of_day\n),\nt_history_regular as (\n  select  [time] = DATEADD(mi, DATEDIFF(mi, getdate(), getutcdate()), \"+(case when @trend_by = 'Daily' \n                          then 'cast(convert(date,hh.collection_time) as datetime)' \n                          else 'dateadd(hour,DATEPART(hour,hh.collection_time),cast(convert(date,hh.collection_time) as datetime))'\n                      end)+\"),\n          hh.srv_name, \n          hh.connection_count\n  from dbo.all_server_volatile_info_history hh\n  where 1=1\n  and exists (select 1/0 from dbo.instance_details id where id.is_enabled = 1 and id.is_alias = 0 and id.sql_instance = hh.srv_name)\n  and hh.srv_name in (select ss.csv_substring from dbo.fn_split_string(@servers,',') ss where ss.srno <= @max_servers_to_display)\n  and hh.collection_time >= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @start_time_utc)\n  and hh.collection_time <= DATEADD(mi, DATEDIFF(mi, GETUTCDATE(), GETDATE()), @end_time_utc)\n  and hh.collection_time > @vih_hourly_collection_time\n  \"+(case when @trend_by = 'Hourly' then '' else '--' end)+\"and datepart(hour,collection_time) = @hour_of_day\n)\n,t_history_regular_to_trendby as (\n  select distinct \n          [time],\n          \"+(case when @parameter_servers_count = 1 then '--' else '' end)+\"hh.srv_name,\n          \"+(case when @percentile = 'p50' then '' else '--' end)+\"connection_count__p50 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(50*0.01) WITHIN GROUP (ORDER BY connection_count) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p95' then '' else '--' end)+\"connection_count__p95 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(95*0.01) WITHIN GROUP (ORDER BY connection_count) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p98' then '' else '--' end)+\"connection_count__p98 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(98*0.01) WITHIN GROUP (ORDER BY connection_count) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p99' then '' else '--' end)+\"connection_count__p99 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(99*0.01) WITHIN GROUP (ORDER BY connection_count) OVER (PARTITION BY [time], srv_name))\n\t\t\t\t\t\"+(case when @percentile = 'p993' then '' else '--' end)+\"connection_count__p993 = CONVERT(NUMERIC(20,2),PERCENTILE_CONT(99.3*0.01) WITHIN GROUP (ORDER BY connection_count) OVER (PARTITION BY [time], srv_name))\n\n  from t_history_regular hh\n  where 1=1\n)\n,t_history as (\n  select * from t_history_hourly\n  union all\n  select * from t_history_regular_to_trendby\n)\nselect *\nfrom t_history\norder by [time]\n\"\nset quoted_identifier on;\nprint @sql\n\nexec dbo.sp_executesql @sql, @params, @start_time_utc, @end_time_utc, @hour_of_day, @servers, @max_servers_to_display, @vih_hourly_collection_time;"
      }
     ]
    }
   ]
  },
  {
   "title": "Other Dashboards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "datasource",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    { "title": "Other Dashboards", "type": "dashlist", "gridPos": { "h": 20, "w": 24, "x": 0, "y": 36 } }
   ]
  }
 ]
}