{
 "title": "SQLMonitor-Alerts",
 "description": "SQL Server Inventory",
 "tags": [
  "mssql",
  "sqlmonitor",
  "inventory",
  "login-expiry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "sqlmonitor_datasource", "label": "SQL Monitor Data Source", "query": "mssql" },
   { "name": "inventory_db", "label": "Inventory Database", "query": "SELECT DB_NAME() as [db_name]" },
   {
    "name": "oncall_team",
    "label": "Alert Owner Team",
    "query": "select team_name\nfrom dbo.sma_oncall_teams\nunion all\nselect '_All_'"
   },
   { "name": "alert_id", "label": "Alert Id" },
   { "name": "alert_key", "label": "Alert Key" },
   { "name": "log_threshold_hours", "label": "Logs History Threshold (Hrs)", "query": "168" },
   {
    "name": "alertengine_website_url",
    "label": "Alert Engine URL",
    "query": "select param_value\nfrom dbo.sma_params p\nwhere 1=1\nand p.param_key = 'url_for_alertengine_website'"
   },
   { "name": "remarks_to_add", "label": "Remarks To Add" }
  ]
 },
 "panels": [
  {
   "title": "Oncall Teams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oncall Teams",
     "type": "table",
     "description": "select * from dbo.sma_oncall_teams",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "dataset": "DBA",
       "rawSql": "declare @sql nvarchar(max);\r\ndeclare @params nvarchar(max);\r\ndeclare @server varchar(125);\r\ndeclare @oncall_team varchar(125);\r\n\r\nset @oncall_team = '${oncall_team}';\r\n\r\nset @server = case when ltrim(rtrim('$server_input')) <> '' then ltrim(rtrim('$server_input')) else null end;\r\nset @params = N'@server varchar(255), @oncall_team varchar(125)';\r\n\r\nset quoted_identifier off;\r\nset @sql = \"\r\n/* $__dashboard */\r\nselect\t[team_name], [description], [team_lead_email], [team_email], [team_lead_slack_account], \r\n\t\t[team_slack_channel], [pagerduty_service_key], [alert_method], [created_by], [created_date_utc]\r\nfrom dbo.sma_oncall_teams ot\r\nwhere 1=1\r\n\"+(case when @oncall_team = '_All_' then '--' else '' end)+\"and team_name = @oncall_team\r\n\";\r\nset quoted_identifier off;\r\n\r\nexec dbo.sp_executesql @sql, @params, @server, @oncall_team;\r\n"
      }
     ]
    }
   ]
  },
  { "title": "Pending Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Pending Alerts",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "dataset": "DBA",
     "rawSql": "declare @sql nvarchar(max);\r\ndeclare @params nvarchar(max);\r\ndeclare @server varchar(125);\r\ndeclare @oncall_team varchar(125);\r\ndeclare @alert_id bigint;\r\ndeclare @alert_key varchar(225);\r\ndeclare @log_threshold_hours int = $log_threshold_hours;\r\ndeclare @grafana_user varchar(225);\r\n\r\nset @oncall_team = '${oncall_team}';\r\nset @grafana_user = case when ltrim(rtrim('${__user.email}')) <> '' then '${__user.email}'\r\n\t\t\t\t\t\t\t\t\t\t\t\t when ltrim(rtrim('${__user.login}')) <> '' then '${__user.login}'\r\n\t\t\t\t\t\t\t\t\t\t\t\t else 'guest'\r\n\t\t\t\t\t\t\t\t\t\t\t\t end;\r\n\r\n\r\nset @server = case when ltrim(rtrim('$server_input')) <> '' then ltrim(rtrim('$server_input')) else null end;\r\nset @alert_id = case when ltrim(rtrim('$alert_id')) <> '' then ltrim(rtrim('$alert_id')) else null end;\r\nset @alert_key = case when ltrim(rtrim('$alert_key')) <> '' then ltrim(rtrim('$alert_key')) else null end;\r\n\r\nset @params = N'@server varchar(255), @oncall_team varchar(125), @alert_id bigint, @alert_key varchar(225), @log_threshold_hours int, @grafana_user varchar(225)';\r\n\r\nset quoted_identifier off;\r\nset @sql = \"\r\ndeclare @all_server_dashboard varchar(500);\r\ndeclare @core_health_panel varchar(500);\r\nselect @all_server_dashboard = p.param_value from dbo.sma_params p where p.param_key = 'GrafanaDashboardPortal';\r\nselect @core_health_panel = p.param_value from dbo.sma_params p where p.param_key = 'url_all_servers_core_health_metrics_dashboard_panel';\r\n\r\nselect\t/* $__dashboard */\r\n\t\t\t\ta.alert_key, created_date_utc, alert_owner_team, [state], severity, [log_header] = header,\r\n\t\t\t\t[last_log] = log_time_utc, logged_by, [log_details] = [description],\r\n\t\t\t\tsuppress_start_date_utc, suppress_end_date_utc, frequency_minutes, [alert_id] = a.id\r\n\r\n\t\t\t\t,[url] = case when a.alert_key in ('Alert-Cpu','Alert-AvailableMemory','Alert-DiskLatency')\r\n\t\t\t\t\t\tthen @core_health_panel\r\n\t\t\t\t\t\telse p.alert_data_url\r\n\t\t\t\t\t\tend\r\n\t\t\t\t,[action_url] = '${alertengine_website_url}alert/take_action?app_name=grafana&user_name='+@grafana_user+'&alert_id='+convert(varchar,a.id)+'&alert_key='+a.alert_key\r\n\t\t\t\t--,[grafana_user] = @grafana_user\r\nfrom dbo.sma_alert a\r\ncross apply (\r\n\tselect\t\"+(case when @alert_id is not null or @alert_key is not null then '--' else '' end)+\"top 1\r\n\t\t\t*\r\n\tfrom dbo.sma_alert_history ah\r\n\twhere 1=1\r\n\tand ah.alert_id = a.id\r\n\tand ah.alert_id_part_no = a.id_part_no\r\n\tand ah.log_time_utc >= dateadd(hour,-@log_threshold_hours,getutcdate())\r\n\torder by ah.log_time_utc desc\r\n) ah\r\nleft join\r\n\t(\r\n\t\tselect\tp.param_key, p.param_value, \r\n\t\t\t\talert_data_url = p.param_value, \r\n\t\t\t\talert_key = case when param_key = 'url_all_servers_alert_history_dashboard_panel' then 'Alert-SqlErrorLog'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_alwayson_latency_dashboard_panel' then 'Alert-AgLatency'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_backups_ag_dbs_dashboard_panel' then 'Alert-AgDbBackupIssue'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_backups_nonag_dbs_dashboard_panel' then 'Alert-NonAgDbBackupIssue'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_core_health_metrics_dashboard_panel' then 'CoreHealthPanel'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_disk_utilization_dashboard_panel' then 'Alert-DiskSpace'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_login_expiry_dashboard_panel' then 'Alert-LoginExpiry'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_logspace_utilization_dashboard_panel' then 'Alert-LogSpace'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_offline_aliases_dashboard_panel' then 'Alert-OfflineServerAlias'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_offline_servers_dashboard_panel' then 'Alert-OfflineServer'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_sqlagent_service_dashboard_panel' then 'Alert-OfflineAgent'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_sqlmonitor_jobs_dashboard_panel' then 'Alert-SqlMonitorJobs'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_tempdb_utilization_dashboard_panel' then 'Alert-Tempdb'\r\n\t\t\t\t\t\t\t\telse null\r\n\t\t\t\t\t\t\t\tend\r\n\t\tfrom dbo.sma_params p where p.param_key like 'url_all_servers_%'\r\n\t) p on p.alert_key = a.alert_key\r\nwhere 1=1\r\nand a.state <> 'Resolved'\r\n\"+(case when @oncall_team = '_All_' then '--' else '' end)+\"and alert_owner_team = @oncall_team\r\n\"+(case when @alert_id is null then '--' else '' end)+\"and a.id = @alert_id and a.id_part_no = @alert_id % 10\r\n\"+(case when @alert_key is null then '--' else '' end)+\"and a.alert_key = @alert_key\r\norder by id, id_part_no\r\n\";\r\nset quoted_identifier off;\r\n\r\nexec dbo.sp_executesql @sql, @params, @server, @oncall_team, @alert_id, @alert_key, @log_threshold_hours, @grafana_user;\r\n"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "dataset": "DBA",
       "rawSql": "declare @sql nvarchar(max);\r\ndeclare @params nvarchar(max);\r\ndeclare @server varchar(125);\r\ndeclare @oncall_team varchar(125);\r\ndeclare @alert_id bigint;\r\ndeclare @alert_key varchar(225);\r\ndeclare @log_threshold_hours int = $log_threshold_hours;\r\ndeclare @grafana_user varchar(225);\r\n\r\nset @oncall_team = '${oncall_team}';\r\nset @grafana_user = case when ltrim(rtrim('${__user.email}')) <> '' then '${__user.email}'\r\n\t\t\t\t\t\t\t\t\t\t\t\t when ltrim(rtrim('${__user.login}')) <> '' then '${__user.login}'\r\n\t\t\t\t\t\t\t\t\t\t\t\t else 'guest'\r\n\t\t\t\t\t\t\t\t\t\t\t\t end;\r\n\r\n\r\nset @server = case when ltrim(rtrim('$server_input')) <> '' then ltrim(rtrim('$server_input')) else null end;\r\nset @alert_id = case when ltrim(rtrim('$alert_id')) <> '' then ltrim(rtrim('$alert_id')) else null end;\r\nset @alert_key = case when ltrim(rtrim('$alert_key')) <> '' then ltrim(rtrim('$alert_key')) else null end;\r\n\r\nset @params = N'@server varchar(255), @oncall_team varchar(125), @alert_id bigint, @alert_key varchar(225), @log_threshold_hours int, @grafana_user varchar(225)';\r\n\r\nset quoted_identifier off;\r\nset @sql = \"\r\ndeclare @all_server_dashboard varchar(500);\r\ndeclare @core_health_panel varchar(500);\r\nselect @all_server_dashboard = p.param_value from dbo.sma_params p where p.param_key = 'GrafanaDashboardPortal';\r\nselect @core_health_panel = p.param_value from dbo.sma_params p where p.param_key = 'url_all_servers_core_health_metrics_dashboard_panel';\r\n\r\nselect\t/* $__dashboard */\r\n\t\t\t\ta.alert_key, created_date_utc, alert_owner_team, [state], severity, [log_header] = header,\r\n\t\t\t\t[last_log] = log_time_utc, logged_by, [log_details] = [description],\r\n\t\t\t\tsuppress_start_date_utc, suppress_end_date_utc, frequency_minutes, [alert_id] = a.id\r\n\t\t\t\t,[url] = case when a.alert_key in ('Alert-Cpu','Alert-AvailableMemory','Alert-DiskLatency')\r\n\t\t\t\t\t\tthen @core_health_panel\r\n\t\t\t\t\t\telse p.alert_data_url\r\n\t\t\t\t\t\tend\r\n\t\t\t\t,[action_url] = '${alertengine_website_url}alert/take_action?app_name=grafana&user_name='+@grafana_user+'&alert_id='+convert(varchar,a.id)+'&alert_key='+a.alert_key\r\n\t\t\t\t--,[grafana_user] = @grafana_user\r\nfrom dbo.sma_alert a\r\ncross apply (\r\n\tselect\t\"+(case when @alert_id is not null or @alert_key is not null then '--' else '' end)+\"top 1\r\n\t\t\t*\r\n\tfrom dbo.sma_alert_history ah\r\n\twhere 1=1\r\n\tand ah.alert_id = a.id\r\n\tand ah.alert_id_part_no = a.id_part_no\r\n\tand ah.log_time_utc >= dateadd(hour,-@log_threshold_hours,getutcdate())\r\n\torder by ah.log_time_utc desc\r\n) ah\r\nleft join\r\n\t(\r\n\t\tselect\tp.param_key, p.param_value, \r\n\t\t\t\talert_data_url = p.param_value, \r\n\t\t\t\tparam_alert_key = case when param_key = 'url_all_servers_alert_history_dashboard_panel' then 'Alert-SqlErrorLog'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_alwayson_latency_dashboard_panel' then 'Alert-AgLatency'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_backups_ag_dbs_dashboard_panel' then 'Alert-AgDbBackupIssue'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_backups_nonag_dbs_dashboard_panel' then 'Alert-NonAgDbBackupIssue'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_core_health_metrics_dashboard_panel' then 'CoreHealthPanel'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_disk_utilization_dashboard_panel' then 'Alert-DiskSpace'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_login_expiry_dashboard_panel' then 'Alert-LoginExpiry'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_logspace_utilization_dashboard_panel' then 'Alert-LogSpace'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_offline_aliases_dashboard_panel' then 'Alert-OfflineServerAlias'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_offline_servers_dashboard_panel' then 'Alert-OfflineServer'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_sqlagent_service_dashboard_panel' then 'Alert-OfflineAgent'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_sqlmonitor_jobs_dashboard_panel' then 'Alert-SqlMonitorJobs'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_tempdb_utilization_dashboard_panel' then 'Alert-Tempdb'\r\n\t\t\t\t\t\t\t\telse null\r\n\t\t\t\t\t\t\t\tend\r\n\t\tfrom dbo.sma_params p where p.param_key like 'url_all_servers_%'\r\n\t) p on p.param_alert_key = a.alert_key\r\nwhere 1=1\r\nand a.state = 'Active'\r\n\"+(case when @oncall_team = '_All_' then '--' else '' end)+\"and alert_owner_team = @oncall_team\r\n\"+(case when @alert_id is null then '--' else '' end)+\"and a.id = @alert_id and a.id_part_no = @alert_id % 10\r\n\"+(case when @alert_key is null then '--' else '' end)+\"and a.alert_key = @alert_key\r\norder by id, id_part_no\r\n\";\r\nset quoted_identifier off;\r\n\r\nexec dbo.sp_executesql @sql, @params, @server, @oncall_team, @alert_id, @alert_key, @log_threshold_hours, @grafana_user;\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Suppressed Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Suppressed Alerts",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "dataset": "DBA",
       "rawSql": "declare @sql nvarchar(max);\r\ndeclare @params nvarchar(max);\r\ndeclare @server varchar(125);\r\ndeclare @oncall_team varchar(125);\r\ndeclare @alert_id bigint;\r\ndeclare @alert_key varchar(225);\r\ndeclare @log_threshold_hours int = $log_threshold_hours;\r\ndeclare @grafana_user varchar(225);\r\n\r\nset @oncall_team = '${oncall_team}';\r\nset @grafana_user = case when ltrim(rtrim('${__user.email}')) <> '' then '${__user.email}'\r\n\t\t\t\t\t\t\t\t\t\t\t\t when ltrim(rtrim('${__user.login}')) <> '' then '${__user.login}'\r\n\t\t\t\t\t\t\t\t\t\t\t\t else 'guest'\r\n\t\t\t\t\t\t\t\t\t\t\t\t end;\r\n\r\n\r\nset @server = case when ltrim(rtrim('$server_input')) <> '' then ltrim(rtrim('$server_input')) else null end;\r\nset @alert_id = case when ltrim(rtrim('$alert_id')) <> '' then ltrim(rtrim('$alert_id')) else null end;\r\nset @alert_key = case when ltrim(rtrim('$alert_key')) <> '' then ltrim(rtrim('$alert_key')) else null end;\r\n\r\nset @params = N'@server varchar(255), @oncall_team varchar(125), @alert_id bigint, @alert_key varchar(225), @log_threshold_hours int, @grafana_user varchar(225)';\r\n\r\nset quoted_identifier off;\r\nset @sql = \"\r\ndeclare @all_server_dashboard varchar(500);\r\ndeclare @core_health_panel varchar(500);\r\nselect @all_server_dashboard = p.param_value from dbo.sma_params p where p.param_key = 'GrafanaDashboardPortal';\r\nselect @core_health_panel = p.param_value from dbo.sma_params p where p.param_key = 'url_all_servers_core_health_metrics_dashboard_panel';\r\n\r\nselect\t/* $__dashboard */\r\n\t\t\t\ta.alert_key, created_date_utc, alert_owner_team, [state], severity, [log_header] = header,\r\n\t\t\t\t[last_log] = log_time_utc, logged_by, [log_details] = [description],\r\n\t\t\t\tsuppress_start_date_utc, suppress_end_date_utc, frequency_minutes, [alert_id] = a.id\r\n\t\t\t\t,[url] = case when a.alert_key in ('Alert-Cpu','Alert-AvailableMemory','Alert-DiskLatency')\r\n\t\t\t\t\t\tthen @core_health_panel\r\n\t\t\t\t\t\telse p.alert_data_url\r\n\t\t\t\t\t\tend\r\n\t\t\t\t,[action_url] = '${alertengine_website_url}alert/take_action?app_name=grafana&user_name='+@grafana_user+'&alert_id='+convert(varchar,a.id)+'&alert_key='+a.alert_key\r\n\t\t\t\t--,[grafana_user] = @grafana_user\r\nfrom dbo.sma_alert a\r\ncross apply (\r\n\tselect\t\"+(case when @alert_id is not null or @alert_key is not null then '--' else '' end)+\"top 1\r\n\t\t\t*\r\n\tfrom dbo.sma_alert_history ah\r\n\twhere 1=1\r\n\tand ah.alert_id = a.id\r\n\tand ah.alert_id_part_no = a.id_part_no\r\n\tand ah.log_time_utc >= dateadd(hour,-@log_threshold_hours,getutcdate())\r\n\torder by ah.log_time_utc desc\r\n) ah\r\nleft join\r\n\t(\r\n\t\tselect\tp.param_key, p.param_value, \r\n\t\t\t\talert_data_url = p.param_value, \r\n\t\t\t\tparam_alert_key = case when param_key = 'url_all_servers_alert_history_dashboard_panel' then 'Alert-SqlErrorLog'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_alwayson_latency_dashboard_panel' then 'Alert-AgLatency'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_backups_ag_dbs_dashboard_panel' then 'Alert-AgDbBackupIssue'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_backups_nonag_dbs_dashboard_panel' then 'Alert-NonAgDbBackupIssue'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_core_health_metrics_dashboard_panel' then 'CoreHealthPanel'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_disk_utilization_dashboard_panel' then 'Alert-DiskSpace'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_login_expiry_dashboard_panel' then 'Alert-LoginExpiry'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_logspace_utilization_dashboard_panel' then 'Alert-LogSpace'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_offline_aliases_dashboard_panel' then 'Alert-OfflineServerAlias'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_offline_servers_dashboard_panel' then 'Alert-OfflineServer'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_sqlagent_service_dashboard_panel' then 'Alert-OfflineAgent'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_sqlmonitor_jobs_dashboard_panel' then 'Alert-SqlMonitorJobs'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_tempdb_utilization_dashboard_panel' then 'Alert-Tempdb'\r\n\t\t\t\t\t\t\t\telse null\r\n\t\t\t\t\t\t\t\tend\r\n\t\tfrom dbo.sma_params p where p.param_key like 'url_all_servers_%'\r\n\t) p on p.param_alert_key = a.alert_key\r\nwhere 1=1\r\nand a.state = 'Suppressed'\r\n\"+(case when @oncall_team = '_All_' then '--' else '' end)+\"and alert_owner_team = @oncall_team\r\n\"+(case when @alert_id is null then '--' else '' end)+\"and a.id = @alert_id and a.id_part_no = @alert_id % 10\r\n\"+(case when @alert_key is null then '--' else '' end)+\"and a.alert_key = @alert_key\r\norder by id, id_part_no\r\n\";\r\nset quoted_identifier off;\r\n\r\nexec dbo.sp_executesql @sql, @params, @server, @oncall_team, @alert_id, @alert_key, @log_threshold_hours, @grafana_user;\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Cleared Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cleared Alerts",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "dataset": "DBA",
       "rawSql": "declare @sql nvarchar(max);\r\ndeclare @params nvarchar(max);\r\ndeclare @server varchar(125);\r\ndeclare @oncall_team varchar(125);\r\ndeclare @alert_id bigint;\r\ndeclare @alert_key varchar(225);\r\ndeclare @log_threshold_hours int = $log_threshold_hours;\r\ndeclare @grafana_user varchar(225);\r\n\r\nset @oncall_team = '${oncall_team}';\r\nset @grafana_user = case when ltrim(rtrim('${__user.email}')) <> '' then '${__user.email}'\r\n\t\t\t\t\t\t\t\t\t\t\t\t when ltrim(rtrim('${__user.login}')) <> '' then '${__user.login}'\r\n\t\t\t\t\t\t\t\t\t\t\t\t else 'guest'\r\n\t\t\t\t\t\t\t\t\t\t\t\t end;\r\n\r\n\r\nset @server = case when ltrim(rtrim('$server_input')) <> '' then ltrim(rtrim('$server_input')) else null end;\r\nset @alert_id = case when ltrim(rtrim('$alert_id')) <> '' then ltrim(rtrim('$alert_id')) else null end;\r\nset @alert_key = case when ltrim(rtrim('$alert_key')) <> '' then ltrim(rtrim('$alert_key')) else null end;\r\n\r\nset @params = N'@server varchar(255), @oncall_team varchar(125), @alert_id bigint, @alert_key varchar(225), @log_threshold_hours int, @grafana_user varchar(225)';\r\n\r\nset quoted_identifier off;\r\nset @sql = \"\r\ndeclare @all_server_dashboard varchar(500);\r\ndeclare @core_health_panel varchar(500);\r\nselect @all_server_dashboard = p.param_value from dbo.sma_params p where p.param_key = 'GrafanaDashboardPortal';\r\nselect @core_health_panel = p.param_value from dbo.sma_params p where p.param_key = 'url_all_servers_core_health_metrics_dashboard_panel';\r\n\r\nselect\t/* $__dashboard */\r\n\t\t\t\ta.alert_key, created_date_utc, alert_owner_team, [state], severity, [log_header] = header,\r\n\t\t\t\t[last_log] = log_time_utc, logged_by, [log_details] = [description],\r\n\t\t\t\tsuppress_start_date_utc, suppress_end_date_utc, frequency_minutes, [alert_id] = a.id\r\n\t\t\t\t,[url] = case when a.alert_key in ('Alert-Cpu','Alert-AvailableMemory','Alert-DiskLatency')\r\n\t\t\t\t\t\tthen @core_health_panel\r\n\t\t\t\t\t\telse p.alert_data_url\r\n\t\t\t\t\t\tend\r\n\t\t\t\t,[action_url] = '${alertengine_website_url}alert/take_action?app_name=grafana&user_name='+@grafana_user+'&alert_id='+convert(varchar,a.id)+'&alert_key='+a.alert_key\r\n\t\t\t\t--,[grafana_user] = @grafana_user\r\nfrom dbo.sma_alert a\r\ncross apply (\r\n\tselect\t\"+(case when @alert_id is not null or @alert_key is not null then '--' else '' end)+\"top 1\r\n\t\t\t*\r\n\tfrom dbo.sma_alert_history ah\r\n\twhere 1=1\r\n\tand ah.alert_id = a.id\r\n\tand ah.alert_id_part_no = a.id_part_no\r\n\tand ah.log_time_utc >= dateadd(hour,-@log_threshold_hours,getutcdate())\r\n\torder by ah.log_time_utc desc\r\n) ah\r\nleft join\r\n\t(\r\n\t\tselect\tp.param_key, p.param_value, \r\n\t\t\t\talert_data_url = p.param_value, \r\n\t\t\t\tparam_alert_key = case when param_key = 'url_all_servers_alert_history_dashboard_panel' then 'Alert-SqlErrorLog'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_alwayson_latency_dashboard_panel' then 'Alert-AgLatency'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_backups_ag_dbs_dashboard_panel' then 'Alert-AgDbBackupIssue'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_backups_nonag_dbs_dashboard_panel' then 'Alert-NonAgDbBackupIssue'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_core_health_metrics_dashboard_panel' then 'CoreHealthPanel'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_disk_utilization_dashboard_panel' then 'Alert-DiskSpace'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_login_expiry_dashboard_panel' then 'Alert-LoginExpiry'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_logspace_utilization_dashboard_panel' then 'Alert-LogSpace'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_offline_aliases_dashboard_panel' then 'Alert-OfflineServerAlias'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_offline_servers_dashboard_panel' then 'Alert-OfflineServer'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_sqlagent_service_dashboard_panel' then 'Alert-OfflineAgent'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_sqlmonitor_jobs_dashboard_panel' then 'Alert-SqlMonitorJobs'\r\n\t\t\t\t\t\t\t\twhen param_key = 'url_all_servers_tempdb_utilization_dashboard_panel' then 'Alert-Tempdb'\r\n\t\t\t\t\t\t\t\telse null\r\n\t\t\t\t\t\t\t\tend\r\n\t\tfrom dbo.sma_params p where p.param_key like 'url_all_servers_%'\r\n\t) p on p.param_alert_key = a.alert_key\r\nwhere 1=1\r\nand a.state = 'Cleared'\r\n\"+(case when @oncall_team = '_All_' then '--' else '' end)+\"and alert_owner_team = @oncall_team\r\n\"+(case when @alert_id is null then '--' else '' end)+\"and a.id = @alert_id and a.id_part_no = @alert_id % 10\r\n\"+(case when @alert_key is null then '--' else '' end)+\"and a.alert_key = @alert_key\r\norder by id, id_part_no\r\n\";\r\nset quoted_identifier off;\r\n\r\nexec dbo.sp_executesql @sql, @params, @server, @oncall_team, @alert_id, @alert_key, @log_threshold_hours, @grafana_user;\r\n"
      }
     ]
    }
   ]
  }
 ]
}